#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(jsonlite); library(sf); library(ggplot2); library(ggrepel); library(geosphere); library(svglite)})
args <- commandArgs(trailingOnly=TRUE); if(length(args)!=1) stop('usage: r_flow_map.R REQUEST_JSON')
req <- fromJSON(args[[1]],simplifyVector=TRUE); if(!identical(req$backend,'r_editorial')) stop('request backend must be r_editorial')
opt <- req$options; tok <- req$design_system$tokens; if (is.null(tok)) tok <- list(); t <- function(k,d) if (is.null(tok[[k]])) d else tok[[k]]; primary<-t('primary','#17656a'); accent<-t('accent','#123d40'); land<-t('land','#ebe8e1'); border<-t('border','#c3beb4'); textc<-t('text','#111111'); muted<-t('muted','#666666'); src <- req$inputs$table; base <- req$inputs$basemap; if(is.null(src)||is.null(base)) stop('flow_map requires inputs.table and inputs.basemap')
d <- read.csv(src,check.names=FALSE); sfld <- ifelse(is.null(opt$source_field),'source',opt$source_field); tfld <- ifelse(is.null(opt$target_field),'target',opt$target_field); vf <- ifelse(is.null(opt$value_field),'value',opt$value_field)
slon <- ifelse(is.null(opt$source_lon_field),'source_lon',opt$source_lon_field); slat <- ifelse(is.null(opt$source_lat_field),'source_lat',opt$source_lat_field); tlon <- ifelse(is.null(opt$target_lon_field),'target_lon',opt$target_lon_field); tlat <- ifelse(is.null(opt$target_lat_field),'target_lat',opt$target_lat_field)
need <- c(sfld,tfld,vf,slon,slat,tlon,tlat); if(!all(need %in% names(d))) stop('flow_map fields missing')
lines <- lapply(seq_len(nrow(d)),function(i){
  a <- c(as.numeric(d[[slon]][i]),as.numeric(d[[slat]][i])); b <- c(as.numeric(d[[tlon]][i]),as.numeric(d[[tlat]][i])); m <- geosphere::gcIntermediate(a,b,n=32,addStartEnd=TRUE,breakAtDateLine=FALSE); st_linestring(m)
})
crs <- ifelse(is.null(opt$crs),'EPSG:8857',opt$crs); flows <- st_sf(d,geometry=st_sfc(lines,crs=4326)) |> st_transform(crs); world <- st_read(base,quiet=TRUE) |> st_transform(crs)
source_pts <- st_as_sf(d,coords=c(slon,slat),crs=4326,remove=FALSE) |> st_transform(crs); target_pts <- st_as_sf(d[!duplicated(d[[tfld]]),],coords=c(tlon,tlat),crs=4326,remove=FALSE) |> st_transform(crs)
label_n <- ifelse(is.null(opt$label_top_n),6,opt$label_top_n); top_idx <- order(d[[vf]],decreasing=TRUE)[seq_len(min(label_n,nrow(d)))]; top_pts <- source_pts[top_idx,]
p <- ggplot() + geom_sf(data=world,fill=land,colour=border,linewidth=.2) + geom_sf(data=flows,aes(linewidth=.data[[vf]]),colour=primary,alpha=.45,lineend='round') + scale_linewidth_continuous(range=c(.3,2.8),guide='none') + geom_sf(data=target_pts,size=2.2,colour=accent) + ggrepel::geom_text_repel(data=top_pts,aes(label=.data[[sfld]],geometry=geometry),stat='sf_coordinates',size=2.6,box.padding=.18,max.overlaps=Inf) + ggrepel::geom_text_repel(data=target_pts,aes(label=.data[[tfld]],geometry=geometry),stat='sf_coordinates',size=2.8,fontface='bold',box.padding=.2,max.overlaps=Inf) + coord_sf(datum=NA) + labs(title=opt$title,subtitle=opt$subtitle,caption=opt$source_note) + theme_void(base_size=10) + theme(plot.title=element_text(size=as.numeric(t('title_size',18)),face='bold',colour=textc),plot.subtitle=element_text(colour=muted),plot.caption=element_text(size=as.numeric(t('source_size',7.5)),colour=muted,hjust=0))
outdir <- req$output_dir; dir.create(outdir,recursive=TRUE,showWarnings=FALSE); out <- file.path(outdir,ifelse(is.null(opt$filename),'figure.svg',opt$filename)); ggsave(out,p,width=12,height=7.2,device=svglite)
writeLines(toJSON(list(schema_version='1.1.0',design_system_id=req$design_system$id,design_system_hash=req$design_system$content_hash,backend='r_editorial',renderer='flow_map',output=out,rows=nrow(d),crs=crs),auto_unbox=TRUE,pretty=TRUE),file.path(outdir,'manifest.json'))
