import { requireBasemap, basemapAdequacy } from './basemap_registry.mjs';
export const MAP_SPEC_VERSION='0.2.0';
const SUPPORTED=new Set(['0.1.0','0.2.0']);
const PROJECTIONS=new Set(['equirectangular']);const LAYER_TYPES=new Set(['observations','line','polygon']);
function extentOk(e){return e&&Number.isFinite(e.west)&&Number.isFinite(e.east)&&Number.isFinite(e.south)&&Number.isFinite(e.north)&&e.west<e.east&&e.south<e.north&&e.west>=-180&&e.east<=180&&e.south>=-90&&e.north<=90;}
function assetAdequacy(asset,task){const rank={coarse:0,low:1,intermediate:2,high:3,full:4};const need=['local','site'].includes(task)?2:0;return {adequate:(rank[asset.detail_class]??-1)>=need,reason:(rank[asset.detail_class]??-1)>=need?'ok':'detail_too_low',task};}
export function validateMapSpec(spec){const errors=[];if(!spec||typeof spec!=='object'||Array.isArray(spec))return {status:'BLOCK',errors:['spec must be an object']};if(!SUPPORTED.has(spec.schema_version))errors.push(`schema_version must be one of ${[...SUPPORTED].join(', ')}`);if(!PROJECTIONS.has(spec.projection))errors.push('projection must be equirectangular');if(spec.crs!=='EPSG:4326')errors.push('crs must be EPSG:4326');if(!extentOk(spec.extent))errors.push('extent is invalid');let basemap=null;
  if(spec.schema_version==='0.2.0'&&spec.basemap_asset){const a=spec.basemap_asset;if(!a.content_hash||!a.source_url||!a.license||!extentOk(a.extent)||!Array.isArray(a.features))errors.push('basemap_asset requires content_hash, source_url, license, extent and features');else{const q=assetAdequacy(a,spec.task||'regional');if(!q.adequate)errors.push(`basemap_inadequate:${q.reason}:${q.task}`);basemap={id:a.id||'inline',content_hash:a.content_hash,source_url:a.source_url,license:a.license,detail_class:a.detail_class};}}
  else{try{const b=requireBasemap(spec.basemap_id);const q=basemapAdequacy(b,spec.extent,spec.task||null);if(!q.adequate)errors.push(`basemap_inadequate:${q.reason}:${q.task}`);basemap={id:b.id,content_hash:b.content_hash,source_url:b.source_url,license:b.license};}catch(e){errors.push(String(e.message||e));}}
  if(!spec.scale||spec.scale.enabled!==true)errors.push('scale.enabled must be true');if(spec.scale?.unit!=='km')errors.push('scale.unit must be km');if(!Array.isArray(spec.layers)||!spec.layers.length)errors.push('layers requires at least one layer');const ids=new Set();for(const [i,l] of (spec.layers||[]).entries()){if(!l||typeof l!=='object'){errors.push(`layers[${i}] invalid`);continue;}if(!l.id||ids.has(l.id))errors.push(`layers[${i}].id missing or duplicate`);else ids.add(l.id);if(!LAYER_TYPES.has(l.type))errors.push(`layers[${i}].type unsupported`);if(l.type==='observations'){if(!Array.isArray(l.points)||!l.points.length)errors.push(`layers[${i}].points required`);for(const [j,p] of (l.points||[]).entries()){if(!Number.isFinite(p.lon)||!Number.isFinite(p.lat))errors.push(`layers[${i}].points[${j}] invalid coordinates`);if(extentOk(spec.extent)&&(p.lon<spec.extent.west||p.lon>spec.extent.east||p.lat<spec.extent.south||p.lat>spec.extent.north))errors.push(`layers[${i}].points[${j}] outside extent`);}if(l.encoding?.color_scale==='rainbow')errors.push(`layers[${i}]:rainbow_color_scale_disallowed`);}}
  if(spec.style_intent&&spec.style_intent!=='nature_scientific_map')errors.push('style_intent must be nature_scientific_map when supplied');return {status:errors.length?'BLOCK':'PASS',errors,basemap};}
export function assertMapSpec(spec){const gate=validateMapSpec(spec);if(gate.status!=='PASS')throw new Error(`MAP_SPEC_BLOCKED: ${gate.errors.join(' | ')}`);return gate;}
