import crypto from 'node:crypto';
const ALLOWED=new Set(['title_size','label_top_n','highlight_max','layout_margins','legend_position','label_offsets','visibility','line_breaks','composition']);
function clone(x){return JSON.parse(JSON.stringify(x));}
function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function hash(v){return crypto.createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
export function validateArtDirectionPatchV2(patch){const e=[]; if(patch?.schema_version!=='2.0.0')e.push('schema_version must be 2.0.0'); if(!patch?.patch_id)e.push('patch_id required'); if(!patch?.story_id)e.push('story_id required'); if(!/^[0-9a-f]{64}$/.test(String(patch?.base_semantic_fingerprint??'')))e.push('valid base_semantic_fingerprint required'); if(!/^[0-9a-f]{64}$/.test(String(patch?.base_design_system_hash??'')))e.push('valid base_design_system_hash required'); for(const [i,op] of (patch?.operations??[]).entries()){if(!op?.target_id)e.push(`operation ${i+1} target_id required`); if(!ALLOWED.has(op?.field))e.push(`operation ${i+1} field '${op?.field}' is protected or unsupported`);} if(!(patch?.operations?.length))e.push('operations required'); return e;}
function applyOp(req,op){req.options=req.options||{}; const ds=req.design_system=req.design_system||{tokens:{},composition:{}}; ds.tokens=ds.tokens||{}; ds.composition=ds.composition||{};
  if(op.field==='title_size') req.options.title_size=Number(op.value);
  else if(op.field==='label_top_n') req.options.label_top_n=Math.max(0,Math.floor(Number(op.value)));
  else if(op.field==='highlight_max') req.options.highlight_max=Boolean(op.value);
  else if(op.field==='layout_margins'){ const v=op.value||{}; for(const k of ['outer_left','outer_right','plot_top','plot_bottom']) if(v[k]!=null) ds.tokens[k]=Number(v[k]); }
  else if(op.field==='composition'){ const v=op.value||{}; for(const [k,val] of Object.entries(v)) ds.composition[k]=String(val); }
  else req.options[op.field]=clone(op.value);
}
export function applyArtDirectionPatchV2(request,patch){const errors=validateArtDirectionPatchV2(patch); if(errors.length)return {status:'INVALID_PATCH',errors,request}; if(request.story_id!==patch.story_id)return {status:'INVALIDATED_STORY',reason:'story_id_mismatch',request}; if(patch.backend&&patch.backend!==request.backend)return {status:'SKIPPED_BACKEND',reason:'backend_scope_mismatch',request}; if(request.semantic_fingerprint!==patch.base_semantic_fingerprint)return {status:'INVALIDATED_SEMANTICS',reason:'semantic_fingerprint_changed',request}; if(request.design_system?.content_hash!==patch.base_design_system_hash)return {status:'INVALIDATED_DESIGN_SYSTEM',reason:'design_system_changed',request}; const out=clone(request); const before=hash(out); for(const op of patch.operations)applyOp(out,op); const protectedAfter={semantic_fingerprint:out.semantic_fingerprint,evidence_hashes:out.evidence_hashes,claim_ids:out.claim_ids,inputs:out.inputs}; const protectedBefore={semantic_fingerprint:request.semantic_fingerprint,evidence_hashes:request.evidence_hashes,claim_ids:request.claim_ids,inputs:request.inputs}; if(hash(protectedAfter)!==hash(protectedBefore))throw new Error('art direction patch modified protected evidence fields'); out.art_direction_patch={patch_id:patch.patch_id,application_status:'APPLIED',operations:patch.operations.map(x=>({target_id:x.target_id,field:x.field}))}; return {status:'APPLIED',request:out,request_hash_before:before,request_hash_after:hash(out),semantic_fingerprint:out.semantic_fingerprint};}
