#!/usr/bin/env python3
from pathlib import Path
import hashlib, json, re

ROOT=Path(__file__).resolve().parents[1]
SKILLS=ROOT/'skills'
OUT=ROOT/'runtime/pi/visual_skill_bundle.mjs'

def parse_skill(path: Path):
    text=path.read_text(encoding='utf-8')
    m=re.match(r'^---\n(.*?)\n---\n(.*)$', text, re.S)
    if not m: raise SystemExit(f'invalid skill frontmatter: {path}')
    fm=m.group(1); body=m.group(2).strip()
    name=re.search(r'^name:\s*(.+)$',fm,re.M)
    desc=re.search(r'^description:\s*(.+)$',fm,re.M)
    if not name or not desc: raise SystemExit(f'missing skill name/description: {path}')
    return {'name':name.group(1).strip(),'description':desc.group(1).strip(),'body':body,'sha256':hashlib.sha256(text.encode()).hexdigest()}

skills={}
for p in sorted(SKILLS.glob('*/SKILL.md')):
    s=parse_skill(p); skills[s['name']]=s
payload=json.dumps(skills,ensure_ascii=False,indent=2)
OUT.write_text("// Generated by scripts/build_visual_skill_bundle.py. Do not edit by hand.\nexport const VISUAL_SKILLS = Object.freeze("+payload+");\n",encoding='utf-8')
print(OUT)
