#!/usr/bin/env python3
from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[1]
CAT=json.loads((ROOT/'config/editorial-design-systems.json').read_text())
systems={x['id']:{'id':x['id'],'description':x['description'],'tokens':x['tokens'],'composition':x['composition']} for x in CAT['systems']}
for v in systems.values():
    raw=json.dumps(v,sort_keys=True,separators=(',',':')).encode(); v['content_hash']=hashlib.sha256(raw).hexdigest()
payload=json.dumps(systems,ensure_ascii=False,indent=2)
code="""// Generated by scripts/build_editorial_design_bundle.py. Do not edit by hand.\nexport const EDITORIAL_DESIGN_SYSTEMS = Object.freeze(%s);\nfunction inferred(recipe={}){\n  const explicit=String(recipe.design_context||'auto'); if(explicit!=='auto'&&EDITORIAL_DESIGN_SYSTEMS[explicit])return explicit;\n  const sf=String(recipe.story_family||''), job=String(recipe.analytical_job||'');\n  if(sf.includes('trajectory')||sf.includes('flight')||job==='movement')return 'movement';\n  if(sf.includes('network')||sf.includes('graph')||job==='network')return 'network';\n  if(sf.includes('flow')||job==='flow')return 'economic';\n  if(sf.includes('terrain')||recipe.terrain||recipe.bathymetry)return 'scientific';\n  if(sf.includes('local')||sf.includes('explainer'))return 'explainer';\n  return 'scientific';\n}\nexport function resolveEditorialDesignSystem(recipe={}){ const id=inferred(recipe); const row=EDITORIAL_DESIGN_SYSTEMS[id]; if(!row)throw new Error(`unknown editorial design system '${id}'`); return row; }\n"""%payload
(ROOT/'runtime/pi/editorial_design_system_bundle.mjs').write_text(code)
print(ROOT/'runtime/pi/editorial_design_system_bundle.mjs')
