#!/usr/bin/env python3
"""Generate runtime/Rust tool-surface derivatives from config/tool-registry.json."""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
REGISTRY_PATH=ROOT/'config'/'tool-registry.json'
RUNTIME_OUT=ROOT/'runtime'/'pi'/'tool_registry.mjs'
RUST_OUT=ROOT/'src'/'tool_registry.rs'

def main()->int:
    data=json.loads(REGISTRY_PATH.read_text(encoding='utf-8'))
    tools=data.get('tools') or []
    names=[row['name'] for row in tools]
    if len(names)!=len(set(names)):
        raise SystemExit('duplicate tool names in tool registry')
    profiles=set(data.get('profiles') or [])
    for row in tools:
        if not row.get('phase') or not row.get('capability_class'):
            raise SystemExit(f'incomplete tool metadata: {row}')
        unknown=set(row.get('profiles') or [])-profiles
        if unknown:
            raise SystemExit(f"unknown profiles for {row['name']}: {sorted(unknown)}")
    js=json.dumps(data,indent=2,ensure_ascii=False)
    RUNTIME_OUT.write_text(
        "// GENERATED by scripts/sync_tool_registry.py. Do not edit by hand.\n"
        f"export const TOOL_REGISTRY = Object.freeze({js});\n"
        "export const TOOL_INDEX = Object.freeze(Object.fromEntries(TOOL_REGISTRY.tools.map(t=>[t.name,Object.freeze(t)])));\n"
        "export const TOOL_NAMES = Object.freeze(TOOL_REGISTRY.tools.map(t=>t.name));\n"
        "export function toolMetadata(name){ return TOOL_INDEX[String(name??'')] ?? null; }\n"
        "export function toolEnabledForProfile(name, profile=TOOL_REGISTRY.default_profile){\n"
        "  const meta=toolMetadata(name); if(!meta) return false;\n"
        "  const requested=String(profile??TOOL_REGISTRY.default_profile).trim()||TOOL_REGISTRY.default_profile;\n"
        "  if(!TOOL_REGISTRY.profiles.includes(requested)) return false;\n"
        "  return meta.agent_visible===true && meta.profiles.includes(requested);\n"
        "}\n",
        encoding='utf-8'
    )
    joined=','.join(names)
    match_arms='\n'.join(f'        "{row["name"]}" => Some("{row["capability_class"]}"),' for row in tools)
    profile_consts=[]
    profile_arms=[]
    for profile in data.get('profiles') or []:
        enabled=','.join(row['name'] for row in tools if profile in (row.get('profiles') or []))
        const_name='NEWSROOM_TOOLS_'+profile.upper().replace('-','_')
        profile_consts.append(f'pub const {const_name}: &str = "{enabled}";')
        profile_arms.append(f'        "{profile}" => Some({const_name}),')
    default_profile=data.get('default_profile') or 'investigate'
    RUST_OUT.write_text(
        '// GENERATED by scripts/sync_tool_registry.py. Do not edit by hand.\n'
        '// Retained as the canonical static registry for contract validation.\n'
        '#[allow(dead_code)]\n'
        f'pub const NEWSROOM_TOOLS: &str = "{joined}";\n'
        f'pub const DEFAULT_TOOL_PROFILE: &str = "{default_profile}";\n'
        + '\n'.join(profile_consts) + '\n\n'
        + 'pub fn tools_for_profile(profile: &str) -> Option<&\'static str> {\n'
        + '    match profile {\n'
        + '\n'.join(profile_arms) + '\n'
        + '        _ => None,\n'
        + '    }\n'
        + '}\n\n'
        + 'pub fn capability_class(name: &str) -> Option<&\'static str> {\n'
        + '    match name {\n'
        + match_arms + '\n'
        + '        _ => None,\n'
        + '    }\n'
        + '}\n\n'
        + 'pub fn is_capability_class(class: Option<&str>) -> bool {\n'
        + '    matches!(class, Some("discovery" | "computation" | "evidence" | "synthesis" | "visual" | "publication"))\n'
        + '}\n',
        encoding='utf-8'
    )
    print(f'tool registry sync: PASS ({len(names)} tools)')
    return 0

if __name__=='__main__':
    raise SystemExit(main())
