#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {renderPublication} from '../runtime/web/publication.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'adn-label-collision-'));
const spec={schema_version:'0.1.0',title:'Collision negative fixture',dek:'Browser QA must fail when scatter text labels overlap even if the SVG stays inside its module.',reader_question:'Can QA detect label-on-label collisions?',visual_thesis:'Overlapping node labels are a release-blocking browser defect.',story_graph_ref:'fixture-story.json',infographic_plan_ref:'fixture-infographic.json',source_note:'Deterministic negative QA fixture.',delivery:{mode:'html',self_contained:true,static_fallback:'png',breakpoints:[390,768],max_initial_bytes:8000000},interaction:{allowed:[],replay:[]},modules:[{id:'collision',type:'plotly',engine:'plotly',visual_type:'network',title:'Two overlapping labels',story_node_ids:['a','b'],explanatory_dimension:'network',width:'wide',spec:{visual_type:'network',figure:{data:[{type:'scatter',mode:'markers+text',x:[0,0.02],y:[0,0],text:['Overlapping label A','Overlapping label B'],textposition:['middle right','middle right'],marker:{size:14}}],layout:{xaxis:{visible:false,range:[-1,1]},yaxis:{visible:false,range:[-1,1]},margin:{l:20,r:20,t:20,b:20},showlegend:false}}}},{id:'context',type:'text',title:'Context',text:'A second explanatory module keeps this a valid PublicationSpec while the plot remains an intentional negative QA fixture.',story_node_ids:['context'],explanatory_dimension:'context',width:'full'}]};
const rendered=renderPublication(spec);const html=path.join(tmp,'index.html'),specPath=path.join(tmp,'publication.json'),out=path.join(tmp,'qa');fs.writeFileSync(html,rendered.html);fs.writeFileSync(specPath,JSON.stringify(spec));
const r=spawnSync('python3',[path.join(ROOT,'runtime/browser/browser_qa.py'),'--html',html,'--spec',specPath,'--output',out],{cwd:ROOT,encoding:'utf8'});assert.equal(r.status,2,`${r.stdout}\n${r.stderr}`);const report=JSON.parse(fs.readFileSync(path.join(out,'browser-qa.json'),'utf8'));assert.equal(report.status,'FAIL');assert.ok(report.errors.some(x=>x.startsWith('plotly_scatter_text_overlap:390:')),JSON.stringify(report.errors));
console.log(JSON.stringify({status:'PASS',expected_failure:report.errors},null,2));
