#!/usr/bin/env node
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {BASEMAP_CONTENT_HASH,BASEMAP_ID,BASEMAP_LICENSE,BASEMAP_SOURCE_URL} from '../runtime/pi/cartography.mjs';
import {lintVizSpec,renderVizBundle,critiqueViz} from '../runtime/pi/viz.mjs';
import {lintInfographicSpec,composeInfographicBundle,critiqueInfographic} from '../runtime/pi/infographic.mjs';
function csv(text){const [h,...ls]=text.trim().split(/\r?\n/),ks=h.split(',');return ls.map(l=>{const vs=l.split(',');return Object.fromEntries(ks.map((k,i)=>[k,/^-?\d+(?:\.\d+)?$/.test(vs[i])?Number(vs[i]):vs[i]]));});}
const flowRows=csv(await readFile(new URL('../fixtures/realdata/eia-us-energy-flow-2024.csv',import.meta.url),'utf8'));
const importRows=csv(await readFile(new URL('../fixtures/v09-realdata/eia-us-crude-imports-2024.csv',import.meta.url),'utf8')).map(r=>({...r,source:r.country,value:r.thousand_bpd}));
const claim='claim-eia-carto-v15',context={verified_claim_ids:[claim]};
const total=flowRows.filter(r=>r.target==='U.S. primary energy').reduce((s,r)=>s+r.quadrillion_btu,0),losses=flowRows.find(r=>r.target==='Electrical system energy losses')?.quadrillion_btu,canada=importRows.find(r=>r.source==='Canada')?.value;
assert.ok(Math.abs(total-94.2)<1e-9&&Math.abs(losses-19.3)<1e-9&&Math.abs(canada-4061.8)<1e-9);
function asset(spec,rows){const lint=lintVizSpec(spec,rows,context);assert.equal(lint.passed,true,lint.blockers.join(' | '));const bundle=renderVizBundle(spec,rows);const d=critiqueViz(spec,rows,lint,bundle.desktop),m=critiqueViz(spec,rows,lint,bundle.mobile);assert.equal(d.passed,true,JSON.stringify(d));assert.equal(m.passed,true,JSON.stringify(m));return{desktopSvg:bundle.desktop,mobileSvg:bundle.mobile,manifest:{claim_id:claim,source_note:spec.source_note,chart_type:spec.chart_type,alt:spec.alt,data_hash:lint.data_hash},critic:{passed:true,score:Math.min(d.score,m.score)},spec,lint};}
const mapSpec={schema_version:'1.0.0',reader_task:'flow',visual_family:'spatial',data_topology:'geo_edges',chart_type:'cartographic_flow_map',title:'Canada dominates the selected crude-import relationships',subtitle:'Selected origins, average thousand barrels per day, 2024',alt:'Natural Earth map shows six selected crude-oil origin-destination relationships into the United States. Canada is by far the largest at about 4.1 million barrels per day. Arcs do not trace physical tanker or pipeline routes.',source_note:'U.S. Energy Information Administration, Petroleum & Other Liquids, 2024 monthly crude-oil imports',note:'Arcs encode country-to-country import relationships. They do not show physical tanker routes or pipeline paths. Country coordinates are representative anchors.',claim_id:claim,sql:'SELECT country AS source,target,source_lat,source_lon,target_lat,target_lon,thousand_bpd AS value FROM eia_imports',unit:'thousand b/d',source_field:'source',target_field:'target',source_lat_field:'source_lat',source_lon_field:'source_lon',target_lat_field:'target_lat',target_lon_field:'target_lon',value_field:'value',geometry_semantics:'abstract_od',geometry_crs:'EPSG:4326',projection:'natural_earth_1',basemap_id:BASEMAP_ID,basemap_source_url:BASEMAP_SOURCE_URL,basemap_license:BASEMAP_LICENSE,basemap_content_hash:BASEMAP_CONTENT_HASH,aggregation_policy:'none',highlight_values:['Canada'],annotations:[]};
const flowSpec={schema_version:'0.9.0',reader_task:'flow',visual_family:'flow',data_topology:'flow_edges',complexity_budget:'medium',chart_type:'sankey',flow_conservation:'strict',flow_tolerance:0.001,title:'Inside the border, energy spreads through a different network',subtitle:'Primary energy, end-use sectors and electrical-system losses, 2024',alt:'Sankey diagram shows five primary energy sources flowing through the U.S. energy balance to end-use sectors and electrical-system losses.',source_note:'U.S. Energy Information Administration, Monthly Energy Review, 2024 energy flow',note:'Published aggregate source, sector and loss totals. The diagram does not imply source-specific allocation to each end-use sector.',claim_id:claim,sql:'SELECT source,target,quadrillion_btu FROM eia_flow',unit:'quadrillion Btu',source_field:'source',target_field:'target',value_field:'quadrillion_btu',highlight_values:['Electrical system energy losses'],annotations:[]};
const assets={'visualizations/v15-crude-map.json':asset(mapSpec,importRows),'visualizations/v15-energy-flow.json':asset(flowSpec,flowRows)};
const spec={schema_version:'1.3.0',competition_profile:'editorial',kicker:'ENERGY / MOVEMENT',layout:'feature',complexity_budget:'medium',quality_target:'publishable',intent:'Connect international crude-oil relationships to the domestic U.S. energy-flow system without implying unverified physical routes.',primary_message:'Geography and system flow answer different questions: Canada dominates selected crude-import relationships, while the domestic energy balance exposes where energy is used and lost.',story_arc:'system',audience:'informed',title:'Two maps of one energy machine',dek:`The United States consumed ${total.toFixed(1)} quadrillion Btu of primary energy in 2024. A cartographic flow map locates selected crude-import relationships; a Sankey then follows the domestic energy balance, including ${losses.toFixed(1)} quads of electrical-system losses.`,alt:'Magazine feature combines a sourced Natural Earth cartographic flow map of selected U.S. crude-import relationships with a Sankey diagram of the 2024 U.S. energy balance.',byline:'Agentic Data Newsroom',date_label:'2024 · EIA real-data validation',source_note:'U.S. Energy Information Administration; Natural Earth 1:110m',mobile_module_order:['opening','crude-map','canada-stat','route-semantics','domestic-section','system-flow','closing'],modules:[
{id:'opening',type:'section_header',span:'full',eyebrow:'Where the system begins',heading:'The same energy story has a geography and a network',deck:'A map can show who supplies whom. A Sankey can show how energy is transformed and lost. The line geometry must keep those claims separate.',story_role:'context',priority:1,emphasis:'primary'},
{id:'crude-map',type:'visual',span:'two_thirds',label:'Selected crude-import relationships',manifest_ref:'visualizations/v15-crude-map.json',story_role:'evidence',priority:1,emphasis:'hero',reader_question:'Where do selected crude-import relationships originate?',claim_set:[claim],new_information:'Adds geographic origin context to the energy system.',explanatory_dimension:'spatial'},
{id:'canada-stat',type:'hero_stat',span:'third',tone:'accent',value:(canada/1000).toFixed(1),unit:'million b/d',label:'Average Canadian crude supplied to the United States in the selected 2024 fixture',detail:'EIA monthly imports averaged across 2024',claim_id:claim,story_role:'hook',priority:1,emphasis:'primary'},
{id:'route-semantics',type:'text',span:'third',label:'What the arcs mean',heading:'Relationship first, route second',body:'The arcs connect representative country anchors and scale with import volume. They do not trace tanker voyages or pipeline geometry. A verified route would require sourced route coordinates under a different geometry semantic.',claim_ids:[claim],story_role:'explanation',priority:2,emphasis:'support'},
{id:'domestic-section',type:'section_header',span:'full',eyebrow:'Inside the border',heading:'The physical system becomes an accounting flow',deck:'Once energy enters the national balance, source totals, end use and electrical-system losses form a different topology.',story_role:'turn',priority:2,emphasis:'secondary'},
{id:'system-flow',type:'visual',span:'full',label:'U.S. energy balance',manifest_ref:'visualizations/v15-energy-flow.json',story_role:'evidence',priority:1,emphasis:'primary',reader_question:'How does primary energy move through the U.S. energy balance?',claim_set:[claim],new_information:'Adds transformation and loss structure that the geographic map cannot encode.',explanatory_dimension:'mechanism'},
{id:'closing',type:'text',span:'full',label:'Cartographic contract',heading:'One line can carry several very different factual meanings',body:'This feature deliberately uses abstract origin-destination arcs for international crude relationships and a Sankey for additive domestic energy flow. v1.5 keeps those semantics explicit so future observed aircraft, vessel or pipeline paths can be shown without silently reusing the same geometry claim.',claim_ids:[claim],story_role:'resolution',priority:3,emphasis:'support'}],scene_graph:{schema_version:'0.1.0',scenes:[{id:'crude-geography',pattern:'hero_sidecar_stack',anchor_module_id:'crude-map',sidecar_module_ids:['canada-stat','route-semantics'],eyebrow:'THE GEOGRAPHY',title:'A relationship map with a hard factual boundary',dek:'Line width carries quantity; line shape is deliberately abstract because the source data do not contain tanker or pipeline routes.'}]}};
const lint=lintInfographicSpec(spec,assets,context);assert.equal(lint.passed,true,lint.blockers.join(' | '));const bundle=composeInfographicBundle(spec,assets),critic=critiqueInfographic(spec,bundle);assert.equal(critic.passed,true,JSON.stringify(critic));
await mkdir(new URL('../outputs/v15-carto-magazine/',import.meta.url),{recursive:true});
await writeFile(new URL('../outputs/v15-carto-magazine/eia-cartographic-flow-feature.svg',import.meta.url),bundle.desktop.svg);await writeFile(new URL('../outputs/v15-carto-magazine/eia-cartographic-flow-feature.mobile.svg',import.meta.url),bundle.mobile.svg);await writeFile(new URL('../outputs/v15-carto-magazine/eia-cartographic-flow-feature.json',import.meta.url),JSON.stringify({spec,lint,critic,dimensions:{desktop:[bundle.desktop.width,Math.round(bundle.desktop.height)],mobile:[bundle.mobile.width,Math.round(bundle.mobile.height)]}},null,2)+'\n');
console.log('v1.5 cartographic magazine feature PASS');console.log(`desktop=${bundle.desktop.width}x${Math.round(bundle.desktop.height)} mobile=${bundle.mobile.width}x${Math.round(bundle.mobile.height)} critic=${critic.score}`);
