#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {compileD3EditorialScene,D3_EDITORIAL_CAPABILITIES} from '../runtime/web/d3_editorial.mjs';
import {compilePlotlyEditorialScene,PLOTLY_EDITORIAL_CAPABILITIES} from '../runtime/web/plotly_editorial.mjs';
import {renderPublication,validatePublicationSpec} from '../runtime/web/publication.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const out=path.join(ROOT,'outputs','v19-browser');fs.mkdirSync(out,{recursive:true});
for(const visual_type of D3_EDITORIAL_CAPABILITIES){const s=compileD3EditorialScene({visual_type,story_node_ids:['fixture'],data:{nodes:[],edges:[]}});assert.equal(s.visual_type,visual_type)}
const minimal={statistical:{data:[{type:'bar',x:['A'],y:[1]}]},sankey:{data:[{type:'sankey',node:{label:['A','B']},link:{source:[0],target:[1],value:[1]}}]},scattergl:{data:[{type:'scattergl',mode:'markers',x:[1],y:[2]}]},parallel_coordinates:{data:[{type:'parcoords',dimensions:[{label:'A',values:[1,2]}]}]},sunburst:{data:[{type:'sunburst',labels:['A'],parents:['']} ]},treemap:{data:[{type:'treemap',labels:['A'],parents:['']} ]},icicle:{data:[{type:'icicle',labels:['A'],parents:['']} ]},surface3d:{data:[{type:'surface',z:[[1,2],[3,4]]}]},network:{data:[{type:'scattergl',mode:'markers',x:[0],y:[0]}]},scientific_map:{data:[{type:'scattergeo',lon:[0],lat:[0],mode:'markers'}]},geo_linked:{data:[{type:'scattergeo',lon:[0],lat:[0],mode:'markers'}]}};
for(const visual_type of PLOTLY_EDITORIAL_CAPABILITIES){const s=compilePlotlyEditorialScene({visual_type,story_node_ids:['fixture'],figure:{...minimal[visual_type],layout:{}}});assert.equal(s.visual_type,visual_type)}
const n=800,x=[],y=[],cluster=[],barX=['Cluster A','Cluster B'],barY=[0,0];for(let i=0;i<n;i++){const a=i%2===0;const t=i*0.071;x.push((a?-1.8:1.8)+Math.sin(t)*0.72+Math.sin(t*.13)*.22);y.push(Math.cos(t*1.7)*.8+Math.cos(t*.17)*.18);cluster.push(a?'A':'B');barY[a?0:1]++}
const spec={schema_version:'0.1.0',title:'Coordinated views stay interactive without flattening the story',dek:'An interactive point view and a coordinated summary chart exercise the browser publication engine and linked-control contract.',reader_question:'Can the publication layer coordinate two views without external runtime requests or separate editorial logic?',visual_thesis:'A linked control can coordinate an exploratory point view and its summary context while preserving the same StoryGraph bindings.',story_graph_ref:'fixtures/v19-browser/dense-story.json',infographic_plan_ref:'fixtures/v19-browser/dense-infographic.json',source_note:'Synthetic deterministic data used only for renderer qualification.',delivery:{mode:'html',self_contained:true,static_fallback:'png',breakpoints:[390,768,1024,1440],max_initial_bytes:8000000},interaction:{allowed:['hover','focus','select','linked_view'],replay:[{action:'click',target:'focus-cluster-a',expect_state:'cluster-a',expect_module_id:'cluster-summary',expect_plotly_title:'Linked view: Cluster A context'}]},modules:[{id:'dense-stat',type:'stat',title:'Observations rendered',value:String(n),unit:'points',story_node_ids:['scale'],explanatory_dimension:'context',width:'third'},{id:'dense-scatter',type:'plotly',engine:'plotly',visual_type:'statistical',title:'Observation cloud',dek:'The control below is replay-tested and also updates the summary chart.',story_node_ids:['observations'],explanatory_dimension:'distribution',width:'wide',spec:{visual_type:'statistical',figure:{data:[{type:'scatter',mode:'markers',x,y,customdata:cluster,marker:{size:5,opacity:.55}}],layout:{margin:{l:36,r:18,t:30,b:36},title:{text:'All observations'},xaxis:{title:'Dimension 1'},yaxis:{title:'Dimension 2'}}},controls:[{id:'focus-cluster-a',label:'Focus Cluster A across views',method:'relayout',args:[{'title.text':'Cluster A highlighted conceptually'}],linked:[{target_module_id:'cluster-summary',method:'relayout',args:[{'title.text':'Linked view: Cluster A context'}]}],state:'cluster-a'}]}},{id:'cluster-summary',type:'plotly',engine:'plotly',visual_type:'statistical',title:'Cluster counts',story_node_ids:['summary'],explanatory_dimension:'comparison',width:'full',spec:{visual_type:'statistical',figure:{data:[{type:'bar',x:barX,y:barY}],layout:{margin:{l:42,r:20,t:34,b:38},title:{text:'All clusters'}}}}}]};
assert.deepEqual(validatePublicationSpec(spec),[]);const rendered=renderPublication(spec);fs.writeFileSync(path.join(out,'advanced-publication.json'),JSON.stringify(spec,null,2)+'\n');fs.writeFileSync(path.join(out,'advanced.html'),rendered.html);fs.writeFileSync(path.join(out,'advanced-manifest.json'),JSON.stringify(rendered.manifest,null,2)+'\n');
console.log(JSON.stringify({status:'PASS',d3_compile_capabilities:D3_EDITORIAL_CAPABILITIES,plotly_compile_capabilities:PLOTLY_EDITORIAL_CAPABILITIES,points:n,initial_bytes:rendered.manifest.initial_bytes},null,2));
