#!/usr/bin/env node
import assert from 'node:assert/strict';import fs from 'node:fs';import {planBackendRouting} from '../runtime/visual/backend_router_v2.mjs';import {compileVisualRecipeV2} from '../runtime/visual/visual_compiler_v2.mjs';
const health=JSON.parse(fs.readFileSync(new URL('../outputs/v19-browser/runtime-health.json',import.meta.url),'utf8')).runtimes;
const base={schema_version:'2.0.0',story_family:'energy_flow',data_profile:{mark_count:12,node_count:0,edge_count:0,estimated_bytes:10000},geography:{enabled:false},network:{enabled:false},annotation:{label_count:8},delivery:{print:false,interactive:true,mobile:true,vector_required:false,animation:false},artifact_mode:'interactive',generated_imagery:false,backend_hints:{allow:[],deny:[],required_capabilities:['interactive_sankey'],qualification_mode:false,challenger_mode:false},analytical_job:'flow'};
const p=planBackendRouting(base,{health});assert.equal(p.backend,'plotly_browser',JSON.stringify(p));assert.deepEqual(p.ranked.map(x=>x.backend),['plotly_browser']);assert.ok(p.hard_filter.rejected.echarts_editorial.some(x=>x.includes('missing_capability')));
const compiled=compileVisualRecipeV2(base,{health});assert.equal(compiled.compile_status,'READY');assert.equal(compiled.primary_backend,'plotly_browser');assert.equal(compiled.execution_graph.at(-1).backend,'plotly_browser');
const graph={...base,story_family:'ownership_network',analytical_job:'network',data_profile:{mark_count:3500,node_count:1200,edge_count:3400,estimated_bytes:4000000},network:{enabled:true,spatial:false,directed:true,weighted:true,community_structure:true,comparison_dense:false},backend_hints:{allow:[],deny:[],required_capabilities:[],qualification_mode:false,challenger_mode:false}};
const gp=planBackendRouting(graph,{health});assert.equal(gp.backend,'networkx_graph',JSON.stringify(gp));const gc=compileVisualRecipeV2(graph,{health});assert.equal(gc.execution_graph[0].backend,'networkx_graph');assert.equal(gc.unresolved.length,0);assert.equal(gc.execution_graph.length,2);assert.equal(gc.execution_graph[1].backend,'plotly_browser');

const radial={...base,story_family:'cold_radial_hierarchy',analytical_job:'hierarchy',data_profile:{mark_count:48,node_count:48,edge_count:47,estimated_bytes:50000},network:{enabled:true,spatial:false,directed:true,weighted:false,community_structure:true,comparison_dense:false},backend_hints:{allow:[],deny:[],required_capabilities:['radial_network','responsive_html'],qualification_mode:false,challenger_mode:false}};
const rp=planBackendRouting(radial,{health});assert.equal(rp.backend,'networkx_graph',JSON.stringify(rp));const rc=compileVisualRecipeV2(radial,{health});assert.equal(rc.compile_status,'READY');assert.deepEqual(rc.execution_graph.map(x=>x.backend),['networkx_graph','plotly_browser']);assert.equal(rc.unresolved.length,0);
const treemap={...base,story_family:'cold_cpi_hierarchy',analytical_job:'composition',data_profile:{mark_count:9,node_count:0,edge_count:0,estimated_bytes:20000},network:{enabled:false},backend_hints:{allow:[],deny:[],required_capabilities:['treemap','responsive_html','claim_annotations'],qualification_mode:false,challenger_mode:false}};
const tp=planBackendRouting(treemap,{health});assert.equal(tp.backend,'plotly_browser',JSON.stringify(tp));const tc=compileVisualRecipeV2(treemap,{health});assert.equal(tc.compile_status,'READY');assert.equal(tc.primary_backend,'plotly_browser');assert.equal(tc.execution_graph.at(-1).backend,'plotly_browser');

console.log('advanced router v1.9 PASS');
