#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {renderPublication,runtimeAssetStatus,validatePublicationSpec} from '../runtime/web/publication.mjs';
import {compileD3EditorialScene} from '../runtime/web/d3_editorial.mjs';
import {validateModelSpec} from '../runtime/visual/model_spec.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const out=path.join(ROOT,'outputs','v19-browser');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
function parseCsv(text){const [h,...rows]=text.trim().split(/\r?\n/);const cols=h.split(',');return rows.map(r=>Object.fromEntries(r.split(',').map((v,i)=>[cols[i],v])))}
const flows=parseCsv(fs.readFileSync(path.join(ROOT,'fixtures/realdata/eia-us-energy-flow-2024.csv'),'utf8')).map(r=>({source:r.source,target:r.target,value:Number(r.quadrillion_btu),unit:'quadrillion Btu'}));
const entityIds=[...new Set(flows.flatMap(f=>[f.source,f.target]))];const model={schema_version:'0.1.0',type:'conserved_flow_system',entities:entityIds.map(id=>({id,label:id,role:id==='U.S. primary energy'||id==='End-use sectors'?'transform':flows.some(f=>f.target===id)?'sink':'source'})),flows,conservation:{nodes:['U.S. primary energy','End-use sectors'],tolerance:1e-9}};
const modelGate=validateModelSpec(model);assert.equal(modelGate.status,'PASS',JSON.stringify(modelGate));assert.equal(modelGate.residuals.length,2);assert.ok(modelGate.residuals.every(r=>Math.abs(r.residual)<1e-9));fs.writeFileSync(path.join(out,'energy-model.json'),JSON.stringify(model,null,2)+'\n');
const graphReq=path.join(ROOT,'fixtures/v19-browser/dandelion-graph.json');const graphOut=path.join(out,'dandelion-analysis.json');const nx=spawnSync('python3',['runtime/browser/networkx_analyze.py','--request',graphReq,'--output',graphOut],{cwd:ROOT,encoding:'utf8'});assert.equal(nx.status,0,nx.stderr||nx.stdout);const graph=JSON.parse(fs.readFileSync(graphOut,'utf8'));assert.equal(graph.summary.node_count,49);assert.equal(graph.summary.layout,'radial_tree');assert.ok(graph.summary.community_count>=2);assert.deepEqual(graph.nodes.find(n=>n.id==='core')&&[graph.nodes.find(n=>n.id==='core').x,graph.nodes.find(n=>n.id==='core').y],[0,0]);
const display=new Map([['U.S. primary energy','Primary energy'],['End-use sectors','End use'],['Electrical system energy losses','Electrical losses']]);const labels=entityIds.map(x=>display.get(x)||x);const idx=new Map(entityIds.map((x,i)=>[x,i]));const source=flows.map(f=>idx.get(f.source)),target=flows.map(f=>idx.get(f.target)),value=flows.map(f=>f.value);
const energySpec={schema_version:'0.1.0',title:'Where U.S. primary energy goes',dek:'A browser publication stress test uses a conservation-checked EIA 2024 flow model, interactive Sankey geometry and a deterministic static archive.',reader_question:'Can the browser publication layer explain the scale and destination of U.S. primary energy flows without losing the underlying conservation model?',visual_thesis:'Most primary energy reaches end-use sectors, while a large explicit branch is recorded as electrical-system losses; the flow widths are tied to a conservation-checked model.',story_graph_ref:'fixtures/v19-browser/eia-energy-story.json',infographic_plan_ref:'fixtures/v19-browser/eia-energy-infographic.json',source_note:'Source: U.S. EIA 2024 aggregate energy-flow fixture bundled with Agentic Data Newsroom.',delivery:{mode:'html',self_contained:true,static_fallback:'png',breakpoints:[390,768,1024,1440],max_initial_bytes:8000000},interaction:{allowed:['hover','focus','select'],replay:[{action:'click',target:'focus-losses',expect_state:'losses'}]},modules:[{id:'loss-stat',type:'stat',engine:'static',title:'Electrical-system losses',dek:'An explicit destination in the verified aggregate flow model.',value:'19.3',unit:'quadrillion Btu',story_node_ids:['losses'],claim_ids:['eia-losses'],explanatory_dimension:'outcome',width:'third'},{id:'energy-flow',type:'plotly',engine:'plotly',visual_type:'sankey',title:'Energy sources converge, then split into use and losses',dek:'Hover any link to inspect the quantity. The interaction button changes the figure title and is replay-tested in Chromium.',story_node_ids:['sources','primary-energy','end-use','losses'],claim_ids:['eia-flow'],explanatory_dimension:'flow',width:'wide',interaction_purpose:'Inspect individual source-to-destination energy flows without crowding the static overview.',spec:{visual_type:'sankey',figure:{data:[{type:'sankey',arrangement:'snap',node:{label:labels,pad:16,thickness:18},link:{source,target,value,valueformat:'.1f',valuesuffix:' QBtu'}}],layout:{font:{family:'Arial',size:11},margin:{l:20,r:20,t:32,b:20},title:{text:'U.S. primary energy flow, 2024'}}},controls:[{id:'focus-losses',label:'Focus the losses branch',method:'restyle',args:[{'link.color':[flows.map(f=>f.target==='Electrical system energy losses'?'rgba(164,61,53,.78)':'rgba(120,128,134,.16)')]},[0]],state:'losses'}]}}]};
assert.deepEqual(validatePublicationSpec(energySpec),[]);const energy=renderPublication(energySpec);assert.equal(energy.manifest.self_contained,true);assert.equal(energy.manifest.runtime_assets.plotly.embedded,true);fs.writeFileSync(path.join(out,'energy-publication.json'),JSON.stringify(energySpec,null,2)+'\n');fs.writeFileSync(path.join(out,'energy.html'),energy.html);fs.writeFileSync(path.join(out,'energy-manifest.json'),JSON.stringify(energy.manifest,null,2)+'\n');
const networkSpec={schema_version:'0.1.0',title:'A dandelion-shaped network stays explorable',dek:'NetworkX computes metrics, communities and a deterministic radial-tree layout. The browser layer renders the result on Canvas so dozens of labels and edges do not have to be frozen into a static SVG.',reader_question:'Can the agent analyze a branching graph and publish a structure-first network view with deterministic geometry and local interaction?',visual_thesis:'The central hub divides into eight first-level branches, each with five leaves; community color and click-to-focus expose the structure without turning the page into a table.',story_graph_ref:'fixtures/v19-browser/dandelion-story.json',infographic_plan_ref:'fixtures/v19-browser/dandelion-infographic.json',source_note:'Synthetic topology used only as an advanced-renderer regression fixture.',delivery:{mode:'html',self_contained:true,static_fallback:'png',breakpoints:[390,768,1024,1440],max_initial_bytes:2000000},interaction:{allowed:['select','focus'],replay:[{action:'click',target:'reset-network',expect_state:'network-reset'}]},modules:[{id:'network-stat',type:'stat',engine:'static',title:'Nodes analyzed',dek:`${graph.summary.edge_count} edges · ${graph.summary.community_count} detected communities`,value:String(graph.summary.node_count),unit:'nodes',story_node_ids:['graph-scale'],explanatory_dimension:'context',width:'third'},{id:'network',type:'model',engine:'native_svg',visual_type:'network',title:'Radial branch structure',dek:'Click a node to highlight its incident edges and inspect its degree/community. Node size is proportional to weighted degree.',story_node_ids:['hub','branches','leaves'],explanatory_dimension:'network',width:'wide',interaction_purpose:'Inspect a dense branching structure one node at a time.',spec:{nodes:graph.nodes,edges:graph.edges,controls:[{id:'reset-network',label:'Reset node focus',action:'reset',state:'network-reset'}]}}]};
assert.deepEqual(validatePublicationSpec(networkSpec),[]);const network=renderPublication(networkSpec);fs.writeFileSync(path.join(out,'network-publication.json'),JSON.stringify(networkSpec,null,2)+'\n');fs.writeFileSync(path.join(out,'network.html'),network.html);fs.writeFileSync(path.join(out,'network-manifest.json'),JSON.stringify(network.manifest,null,2)+'\n');
const d3Scene=compileD3EditorialScene({visual_type:'radial_network',story_node_ids:['hub','branches'],claim_ids:['synthetic-topology'],data:{nodes:graph.nodes.slice(0,9),edges:graph.edges.slice(0,8)}});assert.equal(d3Scene.visual_type,'radial_network');
const assets=runtimeAssetStatus();assert.equal(assets.plotly.available,true);console.log(JSON.stringify({status:'PASS',model:modelGate,network:graph.summary,assets,energy_html_bytes:energy.manifest.initial_bytes,network_html_bytes:network.manifest.initial_bytes},null,2));
