#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {renderPublication,validatePublicationSpec} from '../runtime/web/publication.mjs';
import {resolveEditorialStyle,validateStyleRegistry} from '../runtime/visual/style_mapping.mjs';
import {validateModelSpec} from '../runtime/visual/model_spec.mjs';
import {compileVisualRecipeV2} from '../runtime/visual/visual_compiler_v2.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const OUT=path.join(ROOT,'outputs','v110-systems');fs.rmSync(OUT,{recursive:true,force:true});fs.mkdirSync(OUT,{recursive:true});
const read=(p)=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));const write=(p,v)=>fs.writeFileSync(path.join(OUT,p),typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
assert.deepEqual(validateStyleRegistry(),[]);
const health={};for(const id of ['viz-browser','viz-python','viz-r','viz-qgis','viz-pygmt','viz-density','viz-web'])health[id]={status:id==='viz-browser'?'AVAILABLE':'UNAVAILABLE'};
// 1) Uncertainty: NHC operational two-thirds historical error envelope.
const nhc=read('fixtures/v110-systems/nhc-cone-2026.json');
const uncertaintyModel={schema_version:'0.2.0',type:'probabilistic_interval_series',uncertainty:{coverage:nhc.coverage,coverage_semantics:nhc.coverage_semantics},series:nhc.series};
const ug=validateModelSpec(uncertaintyModel);assert.equal(ug.status,'PASS',JSON.stringify(ug));
const badUncertainty=structuredClone(uncertaintyModel);badUncertainty.series[3].lower=100;const badGate=validateModelSpec(badUncertainty);assert.equal(badGate.status,'BLOCK');
const uncertaintyStyle=resolveEditorialStyle({dimensions:['uncertainty','context'],topologies:['tabular']});assert.equal(uncertaintyStyle.profile,'uncertainty_forecast');
const uRecipe={schema_version:'2.0.0',story_family:'forecast_uncertainty',analytical_job:'time_change',data_profile:{mark_count:24,node_count:0,edge_count:0,estimated_bytes:12000},geography:{enabled:false},network:{enabled:false},annotation:{label_count:8},delivery:{print:false,interactive:true,mobile:true,vector_required:false,animation:false},artifact_mode:'interactive',generated_imagery:false,backend_hints:{allow:[],deny:[],required_capabilities:['uncertainty_band','responsive_html','claim_annotations'],qualification_mode:false,challenger_mode:false}};
const uc=compileVisualRecipeV2(uRecipe,{health});assert.equal(uc.compile_status,'READY');assert.equal(uc.primary_backend,'plotly_browser');
const ux=nhc.series.map(r=>r.horizon),lo=nhc.series.map(r=>r.lower),hi=nhc.series.map(r=>r.upper),mid=nhc.series.map(r=>r.central);
const uncertaintySpec={schema_version:'0.2.0',style_profile:'uncertainty_forecast',title:'Forecast uncertainty grows with lead time',dek:'The 2026 Atlantic operational cone uses historical official-track errors: each circle radius encloses about two-thirds of the previous five years of forecast errors.',reader_question:'How quickly does the operational NHC track uncertainty envelope widen as a forecast extends from 12 to 120 hours?',visual_thesis:'Longer lead times carry materially wider track uncertainty, rising from about ±25 nautical miles at 12 hours to ±200 nautical miles at 120 hours.',story_graph_ref:'v110/nhc-story',infographic_plan_ref:'v110/nhc-infographic',source_note:'Source: NOAA National Hurricane Center, 2026 operational track forecast cone definition. Band shows the historical-error envelope around a zero-error centerline, not a storm track.',delivery:{mode:'html',self_contained:true,static_fallback:'png',breakpoints:[390,768,1024,1440],max_initial_bytes:7000000,max_ready_ms:8000},interaction:{allowed:['hover'],replay:[]},modules:[{id:'coverage',type:'stat',engine:'static',title:'Historical forecast errors enclosed',dek:'Operational cone circle definition for 2026.',value:'≈67',unit:'%',story_node_ids:['coverage'],explanatory_dimension:'context',width:'third'},{id:'uncertainty',type:'plotly',engine:'plotly',visual_type:'statistical',title:'The error envelope widens eightfold by day five',dek:'Distance is shown symmetrically around zero to emphasize uncertainty width rather than imply a forecast path.',story_node_ids:['lead-time','uncertainty-envelope'],explanatory_dimension:'uncertainty',width:'wide',spec:{visual_type:'statistical',figure:{data:[{x:ux,y:lo,type:'scatter',mode:'lines',line:{width:0},hoverinfo:'skip',showlegend:false},{x:ux,y:hi,type:'scatter',mode:'lines',line:{width:0},fill:'tonexty',fillcolor:'rgba(72,108,139,.22)',name:'≈67% historical-error envelope'},{x:ux,y:mid,type:'scatter',mode:'lines+markers',line:{width:2,dash:'dot'},name:'Forecast centerline'}],layout:{margin:{l:60,r:24,t:24,b:88},xaxis:{title:'Forecast lead time (hours)'},yaxis:{title:'Cross-track error distance (nautical miles)',zeroline:true},legend:{orientation:'h',x:0,y:-0.24},showlegend:true}}}}]};
assert.deepEqual(validatePublicationSpec(uncertaintySpec),[]);const ur=renderPublication(uncertaintySpec);write('uncertainty-spec.json',uncertaintySpec);write('uncertainty.html',ur.html);write('uncertainty-manifest.json',ur.manifest);write('uncertainty-model.json',{...uncertaintyModel,gate:ug});
// 2) Linked local world map + magnitude chart using current USGS past-day sample.
const quakes=read('fixtures/v110-systems/usgs-past-day-sample.json').events;const world=read('fixtures/v110-systems/world-outline.json');const m2=quakes.filter(q=>q.mag>=2);
const spatialStyle=resolveEditorialStyle({dimensions:['spatial','distribution'],topologies:['geography','tabular']});assert.equal(spatialStyle.profile,'spatial_monitor');
const gRecipe={...uRecipe,story_family:'realtime_seismic_monitor',analytical_job:'distribution',data_profile:{mark_count:quakes.length,node_count:0,edge_count:0,estimated_bytes:50000},geography:{enabled:true,scale:'global'},backend_hints:{allow:[],deny:[],required_capabilities:['linked_geo_views','responsive_html'],qualification_mode:false,challenger_mode:false}};const gc=compileVisualRecipeV2(gRecipe,{health});assert.equal(gc.primary_backend,'plotly_browser',JSON.stringify(gc));
const names=quakes.map(q=>q.place.length>28?q.place.slice(0,27)+'…':q.place);const names2=m2.map(q=>q.place.length>28?q.place.slice(0,27)+'…':q.place);
const mapBase={type:'scatter',mode:'lines',x:world.lon,y:world.lat,line:{width:.55,color:'rgba(80,92,102,.35)'},hoverinfo:'skip',showlegend:false};
const marker=(rows,name,visible)=>({type:'scatter',mode:'markers',x:rows.map(q=>q.lon),y:rows.map(q=>q.lat),text:rows.map(q=>`${q.place}<br>M ${q.mag} · ${q.depth_km} km deep`),hoverinfo:'text',name,visible,marker:{size:rows.map(q=>5+Math.max(0,q.mag)*2),opacity:.75}});
const bars=(rows,labels,name,visible)=>({type:'bar',orientation:'h',x:rows.map(q=>q.mag),y:labels,name,visible,hovertemplate:'M %{x}<extra></extra>'});
const linkedSpec={schema_version:'0.2.0',style_profile:'spatial_monitor',title:'A live seismic feed is easier to read when place and magnitude stay linked',dek:'A current sample from the USGS past-day feed is shown twice: spatially on a locally rendered equirectangular world outline and as a magnitude comparison. One filter updates both views.',reader_question:'Where are the latest sampled earthquakes, and which of them are large enough to stand out from the mostly small events?',visual_thesis:'Most sampled events are small and clustered in U.S. seismic regions, while the M5.5 event south of Java dominates the magnitude distribution.',story_graph_ref:'v110/usgs-story',infographic_plan_ref:'v110/usgs-infographic',source_note:'Source: USGS All Earthquakes, Past Day feed. This qualification page uses the latest 15 events visible when the fixture was captured.',delivery:{mode:'html',self_contained:true,static_fallback:'png',breakpoints:[390,768,1024,1440],max_initial_bytes:8000000,max_ready_ms:8000},interaction:{allowed:['hover','filter','linked_view'],replay:[{action:'click',target:'m2-only',expect_state:'m2'},{action:'click',target:'all-events',expect_state:'all'}]},modules:[{id:'quake-map',type:'plotly',engine:'plotly',visual_type:'geo_linked',title:'Latest sampled events',dek:'Point size increases with magnitude. Country outlines come from the bundled Natural Earth fixture, so the page makes no external map request.',story_node_ids:['locations','events'],explanatory_dimension:'spatial',width:'wide',interaction_purpose:'Use one filter to focus both the map and magnitude list on M2+ events.',spec:{visual_type:'geo_linked',figure:{data:[mapBase,marker(quakes,'All events',true),marker(m2,'M2+',false)],layout:{margin:{l:28,r:20,t:24,b:42},xaxis:{range:[-180,180],showgrid:false,zeroline:false,title:'Longitude',constrain:'domain'},yaxis:{range:[-60,85],showgrid:false,zeroline:false,title:'Latitude',scaleanchor:'x',scaleratio:1,constrain:'domain'}}},controls:[{id:'m2-only',label:'Show M2+',method:'restyle',args:[{visible:[true,false,true]},[0,1,2]],state:'m2',linked:[{target_module_id:'quake-list',method:'restyle',args:[{visible:[false,true]},[0,1]]}]},{id:'all-events',label:'Show all',method:'restyle',args:[{visible:[true,true,false]},[0,1,2]],state:'all',linked:[{target_module_id:'quake-list',method:'restyle',args:[{visible:[true,false]},[0,1]]}]}]}},{id:'quake-list',type:'plotly',engine:'plotly',visual_type:'statistical',title:'Magnitude comparison',dek:'The same events are sorted by the source feed order; the linked filter switches both views.',story_node_ids:['magnitudes','events'],explanatory_dimension:'distribution',width:'third',spec:{visual_type:'statistical',figure:{data:[bars(quakes,names,'All events',true),bars(m2,names2,'M2+',false)],layout:{margin:{l:150,r:14,t:24,b:40},xaxis:{title:'Magnitude'},yaxis:{automargin:true},showlegend:false}}}}]};
assert.deepEqual(validatePublicationSpec(linkedSpec),[]);const lr=renderPublication(linkedSpec);write('linked-geo-spec.json',linkedSpec);write('linked-geo.html',lr.html);write('linked-geo-manifest.json',lr.manifest);
// 3) Large network: pressure-test native Canvas publication and router, no external graph renderer required below this bound.
const large=read('fixtures/v110-systems/large-network-5000.json');const nStyle=resolveEditorialStyle({dimensions:['network','context'],topologies:['graph_edges']});assert.equal(nStyle.profile,'investigative_network');
const nRecipe={...uRecipe,story_family:'large_relationship_network',analytical_job:'network',data_profile:{mark_count:large.summary.node_count+large.summary.edge_count,node_count:large.summary.node_count,edge_count:large.summary.edge_count,estimated_bytes:5000000},network:{enabled:true,spatial:false,directed:false,weighted:false,community_structure:true,comparison_dense:false},backend_hints:{allow:[],deny:[],required_capabilities:['large_network','interactive_focus','responsive_html'],qualification_mode:false,challenger_mode:false}};const nc=compileVisualRecipeV2(nRecipe,{health});assert.equal(nc.compile_status,'UNRESOLVED');assert.ok(nc.unresolved.includes('final_renderer_unavailable'));assert.equal(nc.primary_backend,'networkx_graph');
const largeSpec={schema_version:'0.2.0',style_profile:'investigative_network',title:'The browser layer can carry a 5,000-node relationship field without freezing it into SVG',dek:'This deterministic scale-free stress fixture tests whether the native Canvas publication path remains responsive before the system reaches for Sigma or Gephi.',reader_question:'At what graph size does the local audited Canvas renderer stop being a credible newsroom fallback for interactive network exploration?',visual_thesis:'At 5,000 nodes and nearly 10,000 edges, the local Canvas path remains fast but the overview becomes a hairball; performance alone cannot qualify a large-network renderer.',story_graph_ref:'v110/large-network-story',infographic_plan_ref:'v110/large-network-infographic',source_note:'Deterministic Barabasi-Albert stress fixture; topology is synthetic and used only for runtime qualification.',delivery:{mode:'html',self_contained:true,static_fallback:'png',breakpoints:[390,768,1024,1440],max_initial_bytes:10000000,max_ready_ms:8000},interaction:{allowed:['select','focus'],replay:[{action:'click',target:'reset-large',expect_state:'large-reset'}]},modules:[{id:'network-scale',type:'stat',engine:'static',title:'Relationship field',dek:`${large.summary.edge_count.toLocaleString()} edges`,value:large.summary.node_count.toLocaleString(),unit:'nodes',story_node_ids:['scale'],explanatory_dimension:'context',width:'third'},{id:'large-network',type:'model',engine:'native_canvas',visual_type:'network',title:'Performance diagnostic: 5,000 nodes on Canvas',dek:'The page remains responsive, but the overview loses structural readability. This diagnostic is intentionally not a large-network editorial PASS.',story_node_ids:['network','hubs'],explanatory_dimension:'network',width:'wide',interaction_purpose:'Inspect individual nodes without forcing every entity label into the overview.',spec:{nodes:large.nodes,edges:large.edges,label_policy:'key',controls:[{id:'reset-large',label:'Reset focus',action:'reset',state:'large-reset'}]}}]};
assert.deepEqual(validatePublicationSpec(largeSpec),[]);const nr=renderPublication(largeSpec);write('large-network-spec.json',largeSpec);write('large-network.html',nr.html);write('large-network-manifest.json',nr.manifest);
// Style incompatibility must fail closed.
const incompatible=resolveEditorialStyle({requested:'investigative_network',dimensions:['uncertainty'],topologies:['tabular']});assert.equal(incompatible.status,'BLOCK');
write('qualification-summary.json',{status:'GENERATED',uncertainty:{model:ug,style:uncertaintyStyle.profile,backend:uc.primary_backend},linked_geo:{style:spatialStyle.profile,backend:gc.primary_backend,event_count:quakes.length},large_network:{style:nStyle.profile,compile_status:nc.compile_status,unresolved:nc.unresolved,primary_backend:nc.primary_backend,summary:large.summary,editorial_verdict:'FAIL_HAIRBALL_SPECIALIST_REQUIRED'},style_negative:incompatible});
console.log(JSON.stringify({status:'PASS',uncertainty_backend:uc.primary_backend,linked_geo_backend:gc.primary_backend,large_compile_status:nc.compile_status,large_unresolved:nc.unresolved,styles:[uncertaintyStyle.profile,spatialStyle.profile,nStyle.profile]},null,2));
