#!/usr/bin/env node
import { resolveDesignSystem } from '../runtime/visual/design_systems.mjs';
import { applyArtDirectionPatchV2, rollbackArtDirectionPatchV2 } from '../runtime/visual/art_direction_replay.mjs';
const semantic='a'.repeat(64); const ds=resolveDesignSystem({story_id:'nasa_climate_trend',story_family:'statistical_editorial'});
const req={schema_version:'1.1.0',backend:'python_publication',story_id:'nasa_climate_trend',semantic_fingerprint:semantic,evidence_hashes:{'e.csv':'b'.repeat(64)},claim_ids:['c1'],inputs:{table:'e.csv'},options:{renderer:'editorial_chart',title:'A factual title'},template:null,design_system:ds};
const patch={schema_version:'2.1.0',patch_id:'p1',story_id:req.story_id,backend:'python_publication',base_semantic_fingerprint:semantic,base_design_system_hash:ds.content_hash,operations:[{operation_id:'title-size',validator_rule_id:'layout.title_hierarchy',scene_id:'scene:hero',object_id:'title',op:'add',path:'/options/title_size',value:26,viewports:['desktop']},{operation_id:'left-margin',validator_rule_id:'layout.safe_area',scene_id:'scene:hero',object_id:'canvas',op:'replace',path:'/design_system/tokens/outer_left',previous_value:ds.tokens.outer_left,value:.06,viewports:['desktop','mobile']}]};
const a=applyArtDirectionPatchV2(req,patch); if(a.status!=='APPLIED')throw new Error(JSON.stringify(a)); if(a.request.options.title!=='A factual title')throw new Error('patch changed protected title content'); if(a.request.semantic_fingerprint!==semantic)throw new Error('semantic fingerprint changed'); if(a.request.options.title_size!==26||a.request.design_system.tokens.outer_left!==.06)throw new Error('presentation patch did not apply');
if(a.diff.length!==2||!a.inverse_patch||!a.affected.viewports.includes('mobile'))throw new Error('patch audit/affected scope missing');
const rolled=rollbackArtDirectionPatchV2(a);if(rolled.status!=='ROLLED_BACK'||rolled.request.design_system.tokens.outer_left!==ds.tokens.outer_left||rolled.request.options.title_size!==undefined)throw new Error('patch rollback failed');
const protectedPatch={...patch,operations:[{...patch.operations[0],path:'/inputs/table'}]};if(applyArtDirectionPatchV2(req,protectedPatch).status!=='INVALID_PATCH')throw new Error('protected path accepted');
const bad={...patch,base_semantic_fingerprint:'c'.repeat(64)}; const b=applyArtDirectionPatchV2(req,bad); if(b.status!=='INVALIDATED_SEMANTICS')throw new Error('semantic invalidation failed');
console.log('art direction replay v1.34: PASS');
