#!/usr/bin/env node
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { lintVizSpec, renderVizBundle, critiqueViz } from '../runtime/pi/viz.mjs';
import { validateInfographicSpec, lintInfographicSpec, composeInfographicBundle, critiqueInfographic } from '../runtime/pi/infographic.mjs';
import { assessEditorialDiscovery, tournamentVisualConcepts, scoreSemanticNovelty } from '../runtime/pi/editorial.mjs';
import { planEditorialAssets, validateExternalAssetManifest, evaluateExpertPreference, summarizeAwardMode } from '../runtime/pi/art_direction.mjs';
import { illustrationAdapterRequest, lintIllustrationSpec, normalizeIllustrationAdapterResponse, critiqueRichIllustration } from '../runtime/pi/illustration.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = join(ROOT, 'outputs', 'nasa-gistemp-v14');
await mkdir(OUT, { recursive: true });
function csv(text){const [head,...lines]=text.trim().split(/\r?\n/);const keys=head.split(',');return lines.map(line=>{const vals=line.split(',');return Object.fromEntries(keys.map((k,i)=>{const raw=vals[i];const num=Number(raw);return[k,raw!==''&&Number.isFinite(num)?num:raw]}));});}
const annual=csv(await readFile(join(ROOT,'fixtures','realdata','nasa-gistemp-1980-2025.csv'),'utf8'));
const monthly=csv(await readFile(join(ROOT,'fixtures','realdata','nasa-gistemp-monthly-2023-2025.csv'),'utf8'));
const claim='claim-nasa-gistemp-2025';
const context={verified_claim_ids:[claim]};
const source='NASA GISS Surface Temperature Analysis v4 (GISTEMP); global land-ocean temperature index';

const lineSpec={schema_version:'0.9.0',reader_task:'change',chart_type:'line',takeaway:'Global temperature anomalies moved from +0.26°C in 1980 to +1.19°C in 2025, with the highest annual value in this series in 2024.',title:'The warming signal is now measured in whole degrees',subtitle:'Global land-ocean temperature anomaly relative to the 1951–1980 mean, 1980–2025',alt:'Line chart showing NASA global temperature anomaly rising from 0.26 degrees Celsius in 1980 to 1.19 degrees in 2025, peaking at 1.29 degrees in 2024.',source_note:source,note:'Annual GISTEMP values. NASA table values divided by 100 to convert hundredths of a degree Celsius to °C.',claim_id:claim,sql:'fixture:nasa-gistemp-1980-2025',unit:'°C',x_field:'year',value_field:'anomaly_c',highlight_values:['2024','2025'],annotations:[{type:'point',text:'2024: +1.29°C, highest annual value in the series',claim_id:claim,match_field:'year',match_value:2024},{type:'point',text:'2025: +1.19°C',claim_id:claim,match_field:'year',match_value:2025}]};
const hottest=[...annual].sort((a,b)=>b.anomaly_c-a.anomaly_c).slice(0,10).map(r=>({year:String(r.year),anomaly_c:r.anomaly_c}));
const rankSpec={schema_version:'0.9.0',reader_task:'ranking',chart_type:'horizontal_bar',takeaway:'Every one of the ten warmest years in the 1980–2025 slice occurred from 2015 onward.',title:'Recent years dominate the top of the temperature ranking',subtitle:'Ten highest annual anomalies in the NASA GISTEMP 1980–2025 slice',alt:'Horizontal bar chart ranking the ten largest annual global temperature anomalies between 1980 and 2025.',source_note:source,note:'Ranking is limited to the 1980–2025 slice used in this visual test.',claim_id:claim,sql:'fixture:nasa-gistemp-1980-2025 top 10',unit:'°C',category_field:'year',value_field:'anomaly_c',sort:'desc',highlight_values:['2024','2025','2023'],annotations:[]};
const heatSpec={schema_version:'0.9.0',reader_task:'distribution',chart_type:'heatmap',takeaway:'Monthly anomalies stayed above +0.88°C throughout 2023–2025.',title:'The recent heat is persistent across the calendar',subtitle:'Monthly global temperature anomaly, 2023–2025, °C above the 1951–1980 mean',alt:'Heatmap with months from January to December and rows for 2023, 2024 and 2025.',source_note:source,note:'Monthly GISTEMP global means; values converted from hundredths of a degree Celsius.',claim_id:claim,sql:'fixture:nasa-gistemp-monthly-2023-2025',unit:'°C',x_field:'month',y_field:'year',value_field:'anomaly_c',annotations:[]};
const processRows=[{source:'Weather stations',target:'GISTEMP analysis',edge:'land air temperature'},{source:'Ships & buoys',target:'GISTEMP analysis',edge:'sea surface temperature'},{source:'Antarctic stations',target:'GISTEMP analysis',edge:'polar observations'},{source:'GISTEMP analysis',target:'Global anomaly',edge:'adjusted global estimate'}];
const processSpec={schema_version:'0.9.0',reader_task:'process',visual_family:'explanatory',data_topology:'process_graph',complexity_budget:'medium',chart_type:'process_schematic',takeaway:'NASA combines land, ocean and Antarctic observations in a globally adjusted temperature analysis.',title:'The headline number comes from a global observation system',subtitle:'Simplified provenance path described by NASA for the GISTEMP analysis',alt:'Process schematic showing weather-station, ship and buoy, and Antarctic observations feeding the GISTEMP analysis.',source_note:'NASA, “NASA Releases Global Temperature Data,” Jan. 14, 2026; NASA GISS GISTEMP v4',note:'Editorial schematic of source categories; it does not represent every processing step in GISTEMP.',claim_id:claim,sql:'source-description:nasa-gistemp-method',unit:'stages',source_field:'source',target_field:'target',edge_label_field:'edge',highlight_values:['GISTEMP analysis'],annotations:[]};

const visualCases=[['warming-line',lineSpec,annual],['hottest-ranking',rankSpec,hottest],['monthly-heatmap',heatSpec,monthly],['gistemp-process',processSpec,processRows]];
const assets={};const results=[];
for(const [name,spec,rows] of visualCases){const lint=lintVizSpec(spec,rows,context);assert.equal(lint.passed,true,`${name}: ${lint.blockers.join(' | ')}`);const bundle=renderVizBundle(spec,rows);const dc=critiqueViz(spec,rows,lint,bundle.desktop);const mc=critiqueViz(spec,rows,lint,bundle.mobile);assets[`visualizations/${name}.json`]={desktopSvg:bundle.desktop,mobileSvg:bundle.mobile,manifest:{claim_id:claim,source_note:spec.source_note,chart_type:spec.chart_type,alt:spec.alt},critic:{passed:dc.passed&&mc.passed,score:Math.min(dc.score,mc.score)}};results.push({name,desktop:dc.score,mobile:mc.score});await writeFile(join(OUT,`${name}.svg`),bundle.desktop);await writeFile(join(OUT,`${name}.mobile.svg`),bundle.mobile);}

const mapSpec={schema_version:'0.2.0',title:'Global observation context',subject:'World geographic context for the NASA GISTEMP measurement system',intent:'Give the global measurement story a recognizable geographic scaffold without inventing station positions or anomaly geography.',alt:'World geographic scaffold derived from Natural Earth Admin 0 country polygons for NASA GISTEMP source categories; observation locations, station density and anomaly intensity are explicitly not encoded.',style_direction:'Restrained editorial GIS context with land shapes and a source-category rail.',aspect_ratio:'landscape',origin_policy:'software_only',source_note:'Natural Earth low-resolution Admin 0 country polygons; NASA GISTEMP source-category description.',credit:'Made with Natural Earth; newsroom GIS render',claim_ids:[claim],evidence_refs:['fixtures/external/naturalearth_lowres/naturalearth_lowres.shp'],factual_elements:[{id:'global-context',label:'Global land context',claim_ids:[claim]}],constraints:['Do not encode observation positions, density, or anomaly intensity.']};
const mapLint=lintIllustrationSpec(mapSpec,{verified_claim_ids:[claim],evidence_refs:mapSpec.evidence_refs});assert.equal(mapLint.passed,true,mapLint.blockers.join(' | '));
const mapRequest=illustrationAdapterRequest(mapSpec,{evidence_snapshot_hash:'nasa-fixture'});
const mapProc=spawnSync('python3',['scripts/natural_earth_map_adapter.py'],{input:JSON.stringify(mapRequest),encoding:'utf8'});assert.equal(mapProc.status,0,mapProc.stderr);
const mapResponse=JSON.parse(mapProc.stdout);const mapNormalized=normalizeIllustrationAdapterResponse(mapSpec,mapResponse);
const mapManifest={schema_version:'0.2.0',kind:'rich_illustration',title:mapSpec.title,subject:mapSpec.subject,alt:mapSpec.alt,source_note:mapSpec.source_note,credit:mapSpec.credit,claim_ids:[claim],evidence_refs:mapSpec.evidence_refs,origin_policy:'software_only',provenance:mapNormalized.provenance,metadata:mapNormalized.metadata};
const mapCritic=critiqueRichIllustration(mapSpec,mapManifest,{desktop:mapNormalized.desktop,mobile:mapNormalized.mobile});assert.equal(mapCritic.passed,true,JSON.stringify(mapCritic));
const sourceManifest={asset_id:'natural-earth-world-context',asset_class:'published_gis',production_lane:'gis_render',source_url:mapResponse.metadata.source_url,license:mapResponse.license,credit:mapResponse.metadata.credit,origin:'software',source_sha256:mapResponse.metadata.source_sha256,output_sha256:(await import('node:crypto')).createHash('sha256').update(mapNormalized.desktop).digest('hex')};assert.deepEqual(validateExternalAssetManifest(sourceManifest),[]);
assets['visualizations/natural-earth-world-context.json']={desktopSvg:mapNormalized.desktop,mobileSvg:mapNormalized.mobile,manifest:mapManifest,critic:mapCritic};
await writeFile(join(OUT,'natural-earth-world-context.svg'),mapNormalized.desktop);await writeFile(join(OUT,'natural-earth-world-context.mobile.svg'),mapNormalized.mobile);await writeFile(join(OUT,'natural-earth-world-context.provenance.json'),JSON.stringify(sourceManifest,null,2)+'\n');

const discovery=assessEditorialDiscovery({reader_problem:'Explain how far the recent global temperature record has shifted and how NASA constructs the number.',candidate_questions:['How far has the long-run baseline shifted?','Is the recent warmth persistent month to month?','How is a global anomaly constructed from observations?','What does the 1951-1980 reference period mean?','Where are the observations collected?'],surprises:['The recent annual cluster remains elevated at monthly resolution.'],counterintuitive_findings:['An anomaly is a comparison with a fixed baseline, not absolute global temperature.'],human_scale_refs:['A global mean aggregates many local measurements.'],spatial_dimensions:['Weather stations, ships, buoys and Antarctic stations form a global observation network.'],temporal_dimensions:['1980-2025 annual trend','2023-2025 monthly persistence'],mechanisms:['Observation categories feed the GISTEMP analysis before the global estimate is reported.'],uncertainties:['The fixture does not contain a full gridded anomaly field.'],missing_reporting:[{need:'Map-ready gridded anomalies for a spatial globe concept',blocking:false,reason:'Useful for a spatial hero, while the measurement-system concept is supported by current evidence.'}],kill_reasons:[]});
assert.equal(discovery.decision,'CONTINUE');
await writeFile(join(OUT,'editorial-discovery.json'),JSON.stringify(discovery,null,2)+'\n');

const base={reader_question:'How did the climate baseline shift and how is the global number known?',editorial_premise:'Connect the long-run warming signal to the observation system and the fixed anomaly baseline.',surprise:'A record-scale annual shift is accompanied by persistent monthly warmth.',mobile_treatment:'Start with the record number, reveal the long signal, explain the fixed baseline, then move to monthly persistence and measurement provenance.',risk_flags:[],reporting_gaps:[],asset_requirements:[]};
const concepts=[
 {...base,concept_id:'measurement-scene',framing:'mechanism',visual_metaphor:'Treat the global estimate as a measurement instrument: observations feed a shared scene whose main readout is the long-run warming signal.',hero_scene:'A long-run signal anchors the scene while the current readout and baseline explanation occupy a sidecar rail.',hero_evidence_refs:['natural-earth-world-context','annual-series','2025-stat','baseline'],supporting_evidence_refs:['monthly-series','method-network'],media_mix:['map','gis','line','object_scene','process','heatmap'],asset_requirements:[{kind:'published GIS world context',available:true,blocking:false}],why_memorable:'The page turns a generic set of climate charts into one measurement story with a clear visual scaffold.',why_reject:''},
 {...base,concept_id:'spatial-globe',framing:'spatial',visual_metaphor:'A globe carries the anomaly field and observation coverage.',hero_scene:'Global spatial anomaly field with observation network and trend rail.',hero_evidence_refs:['annual-series'],supporting_evidence_refs:['method-network'],media_mix:['map','gis','line'],asset_requirements:[{kind:'gridded anomaly geometry',available:false,blocking:true}],why_memorable:'A recognizable globe would make the global mean spatially concrete.',why_reject:'Blocked by missing gridded anomaly geometry.'},
 {...base,concept_id:'baseline-device',framing:'object_scene',visual_metaphor:'A baseline gauge compares the 1951-1980 reference climate with recent readings.',hero_scene:'Reference-period gauge with recent years attached as readings.',hero_evidence_refs:['2025-stat','baseline'],supporting_evidence_refs:['annual-series'],media_mix:['illustration','line'],why_memorable:'A concrete gauge makes the abstract anomaly baseline easier to remember.',why_reject:''},
 {...base,concept_id:'calendar-wall',framing:'temporal',visual_metaphor:'A calendar wall carries the persistent monthly heat while the annual trend is a spine.',hero_scene:'Three-year calendar field with annual context.',hero_evidence_refs:['monthly-series'],supporting_evidence_refs:['annual-series'],media_mix:['heatmap','line'],why_memorable:'The repeated warm cells make persistence visible at a glance.',why_reject:''},
 {...base,concept_id:'human-scale-reading',framing:'human_scale',visual_metaphor:'Translate the global mean into a human-scale measuring device without inventing physical equivalence.',hero_scene:'Measurement metaphor plus verified trend.',hero_evidence_refs:['2025-stat'],supporting_evidence_refs:['annual-series'],media_mix:['illustration','line'],why_memorable:'A recognizable measuring device could make the abstract global mean tangible.',why_reject:'Requires careful editorial framing to avoid false physical equivalence.'},
 {...base,concept_id:'period-compare',framing:'comparison',visual_metaphor:'Two reference worlds compare the fixed baseline period with the recent record.',hero_scene:'Reference period versus recent period with a common scale.',hero_evidence_refs:['baseline','annual-series'],supporting_evidence_refs:['monthly-series'],media_mix:['comparison','line'],why_memorable:'The fixed reference period becomes an explicit visual character in the story.',why_reject:''},
 {...base,concept_id:'progressive-reveal',framing:'progressive_reveal',visual_metaphor:'Reveal annual trend, monthly persistence and measurement method as authored beats.',hero_scene:'Sequential evidence frames.',hero_evidence_refs:['annual-series'],supporting_evidence_refs:['monthly-series','method-network'],media_mix:['line','heatmap','process'],why_memorable:'A controlled sequence protects hierarchy on mobile.',why_reject:'Better suited to browser-native interaction than this static target.'},
 {...base,concept_id:'generic-dashboard',framing:'comparison',visual_metaphor:'A clean data dashboard with standard charts.',hero_scene:'A collection of charts in a magazine layout.',hero_evidence_refs:['annual-series'],supporting_evidence_refs:['ranking','monthly-series'],media_mix:['bar','line','heatmap'],why_memorable:'Clean charts are easy to scan.',why_reject:'Generic module stack repeats evidence and lacks a story-specific premise.'}
];
const tournament=tournamentVisualConcepts({discovery_ref:'outputs/nasa-gistemp-v14/editorial-discovery.json',concepts});
assert.equal(tournament.selected_concept_id,'measurement-scene',JSON.stringify(tournament.scores));
assert.ok(tournament.rejected.length>=5);await writeFile(join(OUT,'visual-concepts.json'),JSON.stringify(tournament,null,2)+'\n');
const assetPlan=planEditorialAssets({concept_ref:'outputs/nasa-gistemp-v14/visual-concepts.json',concept_id:'measurement-scene',requirements:[{id:'world-context',asset_class:'published_gis',status:'required',available:true,purpose:'Recognizable global scaffold for the measurement story',production_lane:'gis_render',source_refs:['fixtures/external/naturalearth_lowres/naturalearth_lowres.shp']},{id:'gridded-anomalies',asset_class:'published_gis',status:'optional',available:false,purpose:'Optional anomaly field for a stronger spatial encoding',production_lane:'gis_render'}]});assert.equal(assetPlan.decision,'CONTINUE');await writeFile(join(OUT,'asset-plan.json'),JSON.stringify(assetPlan,null,2)+'\n');

const redundant=scoreSemanticNovelty({concept_ref:'outputs/nasa-gistemp-v14/visual-concepts.json',modules:[
 {id:'stat-2025',reader_question_id:'recent-warming',claim_set:[claim],new_information:'2025 remained at +1.19 degrees Celsius above the reference mean.',explanatory_dimension:'comparison',dependency_on:[]},
 {id:'warming-line',reader_question_id:'recent-warming',claim_set:[claim],new_information:'The annual series shows the long-run shift from the 1980s to the recent record.',explanatory_dimension:'trend',dependency_on:['stat-2025']},
 {id:'hottest-ranking',reader_question_id:'recent-warming',claim_set:[claim],new_information:'The highest-ranked annual anomalies are concentrated in recent years.',explanatory_dimension:'rank',dependency_on:[]},
 {id:'monthly-heatmap',reader_question_id:'monthly-persistence',claim_set:[claim],new_information:'Monthly anomalies stay elevated across the 2023-2025 calendar.',explanatory_dimension:'distribution',dependency_on:['warming-line']},
 {id:'gistemp-process',reader_question_id:'measurement-method',claim_set:[claim],new_information:'Land ocean and Antarctic observation categories feed the GISTEMP estimate.',explanatory_dimension:'mechanism',dependency_on:[]}
]});
const rankingDecision=redundant.decisions.find(item=>item.module_id==='hottest-ranking');assert.equal(rankingDecision.redundancy,'high');
const novelty=scoreSemanticNovelty({concept_ref:'outputs/nasa-gistemp-v14/visual-concepts.json',modules:[redundant.modules[0],redundant.modules[1],redundant.modules[3],redundant.modules[4],{id:'baseline',reader_question_id:'baseline-meaning',claim_set:[claim],new_information:'Each anomaly is measured against the fixed 1951-1980 reference mean.',explanatory_dimension:'context',dependency_on:['warming-line']}]});
assert.equal(novelty.passed,true,JSON.stringify(novelty.decisions));await writeFile(join(OUT,'semantic-novelty.json'),JSON.stringify({rejected_module:rankingDecision,final:novelty},null,2)+'\n');

const pageSpec={schema_version:'1.3.0',competition_profile:'oja2026_visual',editorial_discovery_ref:'editorial/discovery/nasa.json',visual_concept_ref:'editorial/concepts/nasa.json',selected_concept_id:'measurement-scene',novelty_ref:'editorial/novelty/nasa.json',asset_plan_ref:'editorial/assets/nasa.json',kicker:'CLIMATE / DATA FEATURE',title:'The heat stayed near record territory',dek:'NASA’s global temperature record shows a long-run shift that remains visible month after month, while the headline number is built from observations across land, ocean and Antarctica.',alt:'A magazine-style climate feature organized around one integrated warming scene, with a long-run temperature line, a 2025 readout, a baseline explanation, a monthly heatmap and a schematic of NASA’s observation system.',byline:'Agentic Data Newsroom',date_label:'v1.4 editorial-intelligence QA',layout:'feature',complexity_budget:'exploratory',source_note:'NASA GISS Surface Temperature Analysis v4; NASA Global Temperature release, 2026',intent:'Explain the long-run shift, recent persistence and measurement provenance in one integrated visual story.',primary_message:'Recent global temperature anomalies remain far above the late-20th-century range, and NASA derives the global estimate from a distributed observation system.',story_arc:'explain',audience:'general',quality_target:'award',mobile_module_order:['stat-2025','world-context','warming-line','baseline','section-months','monthly-heatmap','gistemp-process'],scene_graph:{schema_version:'0.1.0',scenes:[{id:'warming-measurement-scene',pattern:'hero_sidecar_stack',eyebrow:'The global readout',title:'One measurement, seen in place and time',dek:'A sourced world scaffold makes the global scope tangible; the long-run signal, current readout and fixed baseline stay attached to the same scene.',anchor_module_id:'world-context',sidecar_module_ids:['warming-line','stat-2025','baseline'],shared_source_scope:true}]},modules:[
 {id:'world-context',type:'illustration',span:'two_thirds',label:'Global observation context',asset_ref:'visualizations/natural-earth-world-context.json',alt:mapSpec.alt,credit:mapSpec.credit,claim_ids:[claim],story_role:'context',priority:1,emphasis:'hero',reader_question_id:'measurement-geography',claim_set:[claim],new_information:'The headline estimate is global and combines land, ocean and Antarctic observation categories, while this map intentionally does not encode station positions.',explanatory_dimension:'spatial'},
 {id:'stat-2025',type:'hero_stat',span:'third',tone:'accent',value:'+1.19',unit:'°C',label:'2025 global annual anomaly above the 1951–1980 mean',detail:'NASA GISTEMP v4',claim_id:claim,story_role:'hook',priority:1,emphasis:'primary',reader_question_id:'recent-warming',claim_set:[claim],new_information:'2025 remained at +1.19°C above the reference mean.',explanatory_dimension:'comparison'},
 {id:'warming-line',type:'visual',span:'two_thirds',label:'The long signal',manifest_ref:'visualizations/warming-line.json',story_role:'evidence',priority:1,emphasis:'primary',reader_question_id:'recent-warming',claim_set:[claim],new_information:'The annual series shows the long-run shift from the 1980s to the recent record.',explanatory_dimension:'trend',dependency_on:['stat-2025']},
 {id:'baseline',type:'text',span:'third',label:'Reading the anomaly',heading:'The baseline stays fixed',body:'NASA reports departures from the 1951–1980 mean. Keeping the reference period fixed makes the annual values directly comparable across the series.',claim_ids:[claim],story_role:'explanation',priority:2,emphasis:'secondary',reader_question_id:'baseline-meaning',claim_set:[claim],new_information:'Each anomaly is measured against the fixed 1951-1980 reference mean.',explanatory_dimension:'context',dependency_on:['warming-line']},
 {id:'section-months',type:'section_header',span:'full',eyebrow:'Inside the recent years',heading:'The warmth persists month after month',deck:'The annual average is supported by repeated elevated months, then the story turns to how the estimate is constructed.',story_role:'turn',priority:2,emphasis:'secondary'},
 {id:'monthly-heatmap',type:'visual',span:'two_thirds',label:'Monthly persistence',manifest_ref:'visualizations/monthly-heatmap.json',story_role:'evidence',priority:2,emphasis:'primary',reader_question_id:'monthly-persistence',claim_set:[claim],new_information:'Monthly anomalies stay elevated across the 2023-2025 calendar.',explanatory_dimension:'distribution',dependency_on:['warming-line']},
 {id:'gistemp-process',type:'visual',span:'third',label:'How the number is built',manifest_ref:'visualizations/gistemp-process.json',story_role:'resolution',priority:2,emphasis:'secondary',reader_question_id:'measurement-method',claim_set:[claim],new_information:'Land ocean and Antarctic observations feed the global estimate.',explanatory_dimension:'mechanism'}
]};
assert.deepEqual(validateInfographicSpec(pageSpec),[]);const pageLint=lintInfographicSpec(pageSpec,assets,context);assert.equal(pageLint.passed,true,pageLint.blockers.join(' | '));const pageBundle=composeInfographicBundle(pageSpec,assets);const pageCritic=critiqueInfographic(pageSpec,pageBundle);assert.equal(pageCritic.passed,true,JSON.stringify(pageCritic));
assert.equal(pageBundle.desktop.scenes.length,1);assert.match(pageBundle.desktop.svg,/data-role="scene-boundary" data-scene-id="warming-measurement-scene"/);assert.doesNotMatch(pageBundle.desktop.svg,/THE RECENT CLUSTER/);assert.match(pageBundle.desktop.svg,/Made with Natural Earth/);assert.match(pageBundle.desktop.svg,/>01 · 2025 GLOBAL ANNUAL ANOMALY/);assert.match(pageBundle.mobile.svg,/>01 · 2025 GLOBAL ANNUAL ANOMALY/);assert.match(pageBundle.desktop.svg,/>03 · READING THE ANOMALY/);assert.match(pageBundle.mobile.svg,/>03 · READING THE ANOMALY/);assert.ok(pageBundle.desktop.height<2500,`scene page too tall: ${pageBundle.desktop.height}`);
const alternateSpec=structuredClone(pageSpec);
alternateSpec.scene_graph={schema_version:'0.1.0',scenes:[{id:'warming-measurement-rail',pattern:'hero_with_rail',eyebrow:'The global readout',title:'The world first, evidence underneath',dek:'A second bounded prototype tests whether a full-width geographic scaffold creates a stronger opening rhythm before supporting evidence.',anchor_module_id:'world-context',sidecar_module_ids:['warming-line','stat-2025','baseline'],shared_source_scope:true}]};
const alternateBundle=composeInfographicBundle(alternateSpec,assets);const alternateCritic=critiqueInfographic(alternateSpec,alternateBundle);assert.equal(alternateCritic.passed,true,JSON.stringify(alternateCritic));
await writeFile(join(OUT,'nasa-gistemp-v14.alt.svg'),alternateBundle.desktop.svg);await writeFile(join(OUT,'nasa-gistemp-v14.alt.mobile.svg'),alternateBundle.mobile.svg);
const preference=evaluateExpertPreference({baseline_ref:'outputs/nasa-gistemp-realdata/nasa-gistemp-feature.png',candidate_ref:'outputs/nasa-gistemp-v14/nasa-gistemp-v14.png',minimum_reviewers:3,candidate_threshold:0.7,reviews:[]});assert.equal(preference.status,'PENDING');
await writeFile(join(OUT,'expert-preference.json'),JSON.stringify(preference,null,2)+'\n');
const awardStatus=summarizeAwardMode({discovery_ref:'outputs/nasa-gistemp-v14/editorial-discovery.json',concepts_ref:'outputs/nasa-gistemp-v14/visual-concepts.json',asset_plan_ref:'outputs/nasa-gistemp-v14/asset-plan.json',novelty_ref:'outputs/nasa-gistemp-v14/semantic-novelty.json',page_ref:'outputs/nasa-gistemp-v14/nasa-gistemp-v14.json',preference_ref:'outputs/nasa-gistemp-v14/expert-preference.json',preference_status:preference.status,metrics:{concepts_generated:concepts.length,concepts_killed:tournament.rejected.length,research_gap_requests:discovery.missing_reporting.length,prototype_count:2,raster_revision_count:1,provider_tokens:0,provider_cost_usd:0,wall_time_ms:0,human_review_count:0}});assert.equal(awardStatus.status,'READY_FOR_HUMAN');
await writeFile(join(OUT,'award-mode-status.json'),JSON.stringify(awardStatus,null,2)+'\n');
await writeFile(join(OUT,'prototype-comparison.json'),JSON.stringify({selected:{pattern:pageSpec.scene_graph.scenes[0].pattern,critic:pageCritic.score,height:pageBundle.desktop.height},alternate:{pattern:alternateSpec.scene_graph.scenes[0].pattern,critic:alternateCritic.score,height:alternateBundle.desktop.height},human_preference:preference.status},null,2)+'\n');
await writeFile(join(OUT,'nasa-gistemp-v14.svg'),pageBundle.desktop.svg);await writeFile(join(OUT,'nasa-gistemp-v14.mobile.svg'),pageBundle.mobile.svg);await writeFile(join(OUT,'nasa-gistemp-v14.json'),JSON.stringify({pageSpec,pageLint,pageCritic,editorial:{discovery,tournament,novelty,rejected:rankingDecision,assetPlan},layout:{desktop:{height:pageBundle.desktop.height,strategy:pageBundle.desktop.layout_strategy,scenes:pageBundle.desktop.scenes},mobile:{height:pageBundle.mobile.height}}},null,2)+'\n');await writeFile(join(OUT,'summary.json'),JSON.stringify({visuals:results,editorial:{decision:discovery.decision,concepts:concepts.length,finalists:tournament.finalists,rejected:tournament.rejected.length,ranking_redundancy:rankingDecision.max_overlap,final_average_novelty:novelty.average_novelty,external_asset_origin:sourceManifest.origin,asset_plan_decision:assetPlan.decision,award_mode_status:awardStatus.status,human_preference:preference.status,prototype_count:2},page:{critic:pageCritic.score,desktopHeight:pageBundle.desktop.height,mobileHeight:pageBundle.mobile.height,desktopStrategy:pageBundle.desktop.layout_strategy}},null,2)+'\n');
console.log(`v1.4 NASA: concepts=${concepts.length} rejected=${tournament.rejected.length} ranking_overlap=${rankingDecision.max_overlap}`);console.log(`page critic=${pageCritic.score}/100 desktop=${pageBundle.desktop.height.toFixed(1)} mobile=${pageBundle.mobile.height.toFixed(1)} strategy=${pageBundle.desktop.layout_strategy}`);
