// GENERATED by scripts/sync_tool_registry.py. Do not edit by hand.
// Retained as the canonical static registry for contract validation.
#[allow(dead_code)]
pub const NEWSROOM_TOOLS: &str = "artifact_inventory,newsroom_update_plan,news_search,fetch_url,download_data,duckdb_query,newsroom_parallel_tasks,newsroom_visual_backend_status,newsroom_graph_extraction_status,newsroom_visual_skill,newsroom_visual_backend_plan,newsroom_viz_plan,newsroom_viz_lint,newsroom_viz_render,newsroom_viz_critic,newsroom_explainer_plan,newsroom_explainer_lint,newsroom_explainer_render,newsroom_explainer_critic,newsroom_illustration_plan,newsroom_illustration_lint,newsroom_illustration_generate,newsroom_illustration_critic,newsroom_editorial_discovery,newsroom_story_graph,newsroom_visual_concepts,newsroom_semantic_novelty,newsroom_asset_requirements,newsroom_reference_patterns,newsroom_expert_preference_record,newsroom_award_mode_status,newsroom_infographic_plan,newsroom_infographic_lint,newsroom_infographic_render,newsroom_infographic_critic,newsroom_model_validate,newsroom_basemap_prepare,newsroom_map_validate,newsroom_style_map,newsroom_publication_plan,newsroom_publication_render,newsroom_publication_qa,newsroom_network_analyze,newsroom_network_reduce,newsroom_infographic_preview,newsroom_infographic_vision_critic,newsroom_infographic_revise,newsroom_competition_preflight,newsroom_chart,record_claim";
pub const DEFAULT_TOOL_PROFILE: &str = "investigate";
pub const NEWSROOM_TOOLS_INVESTIGATE: &str = "artifact_inventory,newsroom_update_plan,news_search,fetch_url,download_data,duckdb_query,newsroom_parallel_tasks,newsroom_viz_plan,newsroom_viz_lint,newsroom_viz_render,newsroom_viz_critic,newsroom_story_graph,newsroom_chart,record_claim";
pub const NEWSROOM_TOOLS_VISUAL: &str = "artifact_inventory,newsroom_update_plan,news_search,fetch_url,download_data,duckdb_query,newsroom_parallel_tasks,newsroom_viz_plan,newsroom_viz_lint,newsroom_viz_render,newsroom_viz_critic,newsroom_explainer_plan,newsroom_explainer_lint,newsroom_explainer_render,newsroom_explainer_critic,newsroom_illustration_plan,newsroom_illustration_lint,newsroom_illustration_generate,newsroom_illustration_critic,newsroom_editorial_discovery,newsroom_story_graph,newsroom_visual_concepts,newsroom_semantic_novelty,newsroom_asset_requirements,newsroom_reference_patterns,newsroom_infographic_plan,newsroom_infographic_lint,newsroom_infographic_render,newsroom_infographic_critic,newsroom_infographic_preview,newsroom_infographic_vision_critic,newsroom_infographic_revise,record_claim";
pub const NEWSROOM_TOOLS_PUBLICATION: &str = "artifact_inventory,newsroom_update_plan,newsroom_story_graph,newsroom_publication_plan,newsroom_publication_render,newsroom_publication_qa,newsroom_competition_preflight,record_claim";
pub const NEWSROOM_TOOLS_COMPETITION: &str = "artifact_inventory,newsroom_update_plan,news_search,fetch_url,download_data,duckdb_query,newsroom_parallel_tasks,newsroom_visual_backend_status,newsroom_graph_extraction_status,newsroom_visual_skill,newsroom_visual_backend_plan,newsroom_viz_plan,newsroom_viz_lint,newsroom_viz_render,newsroom_viz_critic,newsroom_explainer_plan,newsroom_explainer_lint,newsroom_explainer_render,newsroom_explainer_critic,newsroom_illustration_plan,newsroom_illustration_lint,newsroom_illustration_generate,newsroom_illustration_critic,newsroom_editorial_discovery,newsroom_story_graph,newsroom_visual_concepts,newsroom_semantic_novelty,newsroom_asset_requirements,newsroom_reference_patterns,newsroom_expert_preference_record,newsroom_award_mode_status,newsroom_infographic_plan,newsroom_infographic_lint,newsroom_infographic_render,newsroom_infographic_critic,newsroom_model_validate,newsroom_basemap_prepare,newsroom_map_validate,newsroom_style_map,newsroom_publication_plan,newsroom_publication_render,newsroom_publication_qa,newsroom_network_analyze,newsroom_network_reduce,newsroom_infographic_preview,newsroom_infographic_vision_critic,newsroom_infographic_revise,newsroom_competition_preflight,newsroom_chart,record_claim";
pub const NEWSROOM_TOOLS_FULL: &str = "artifact_inventory,newsroom_update_plan,news_search,fetch_url,download_data,duckdb_query,newsroom_parallel_tasks,newsroom_visual_backend_status,newsroom_graph_extraction_status,newsroom_visual_skill,newsroom_visual_backend_plan,newsroom_viz_plan,newsroom_viz_lint,newsroom_viz_render,newsroom_viz_critic,newsroom_explainer_plan,newsroom_explainer_lint,newsroom_explainer_render,newsroom_explainer_critic,newsroom_illustration_plan,newsroom_illustration_lint,newsroom_illustration_generate,newsroom_illustration_critic,newsroom_editorial_discovery,newsroom_story_graph,newsroom_visual_concepts,newsroom_semantic_novelty,newsroom_asset_requirements,newsroom_reference_patterns,newsroom_expert_preference_record,newsroom_award_mode_status,newsroom_infographic_plan,newsroom_infographic_lint,newsroom_infographic_render,newsroom_infographic_critic,newsroom_model_validate,newsroom_basemap_prepare,newsroom_map_validate,newsroom_style_map,newsroom_publication_plan,newsroom_publication_render,newsroom_publication_qa,newsroom_network_analyze,newsroom_network_reduce,newsroom_infographic_preview,newsroom_infographic_vision_critic,newsroom_infographic_revise,newsroom_competition_preflight,newsroom_chart,record_claim";

pub fn tools_for_profile(profile: &str) -> Option<&'static str> {
    match profile {
        "investigate" => Some(NEWSROOM_TOOLS_INVESTIGATE),
        "visual" => Some(NEWSROOM_TOOLS_VISUAL),
        "publication" => Some(NEWSROOM_TOOLS_PUBLICATION),
        "competition" => Some(NEWSROOM_TOOLS_COMPETITION),
        "full" => Some(NEWSROOM_TOOLS_FULL),
        _ => None,
    }
}

pub fn capability_class(name: &str) -> Option<&'static str> {
    match name {
        "artifact_inventory" => Some("discovery"),
        "newsroom_update_plan" => Some("planning"),
        "news_search" => Some("discovery"),
        "fetch_url" => Some("discovery"),
        "download_data" => Some("discovery"),
        "duckdb_query" => Some("computation"),
        "newsroom_parallel_tasks" => Some("synthesis"),
        "newsroom_visual_backend_status" => Some("meta"),
        "newsroom_graph_extraction_status" => Some("meta"),
        "newsroom_visual_skill" => Some("meta"),
        "newsroom_visual_backend_plan" => Some("synthesis"),
        "newsroom_viz_plan" => Some("visual"),
        "newsroom_viz_lint" => Some("visual"),
        "newsroom_viz_render" => Some("visual"),
        "newsroom_viz_critic" => Some("visual"),
        "newsroom_explainer_plan" => Some("visual"),
        "newsroom_explainer_lint" => Some("visual"),
        "newsroom_explainer_render" => Some("visual"),
        "newsroom_explainer_critic" => Some("visual"),
        "newsroom_illustration_plan" => Some("visual"),
        "newsroom_illustration_lint" => Some("visual"),
        "newsroom_illustration_generate" => Some("visual"),
        "newsroom_illustration_critic" => Some("visual"),
        "newsroom_editorial_discovery" => Some("synthesis"),
        "newsroom_story_graph" => Some("synthesis"),
        "newsroom_visual_concepts" => Some("synthesis"),
        "newsroom_semantic_novelty" => Some("synthesis"),
        "newsroom_asset_requirements" => Some("synthesis"),
        "newsroom_reference_patterns" => Some("synthesis"),
        "newsroom_expert_preference_record" => Some("synthesis"),
        "newsroom_award_mode_status" => Some("meta"),
        "newsroom_infographic_plan" => Some("visual"),
        "newsroom_infographic_lint" => Some("visual"),
        "newsroom_infographic_render" => Some("visual"),
        "newsroom_infographic_critic" => Some("visual"),
        "newsroom_model_validate" => Some("computation"),
        "newsroom_basemap_prepare" => Some("synthesis"),
        "newsroom_map_validate" => Some("computation"),
        "newsroom_style_map" => Some("synthesis"),
        "newsroom_publication_plan" => Some("publication"),
        "newsroom_publication_render" => Some("publication"),
        "newsroom_publication_qa" => Some("publication"),
        "newsroom_network_analyze" => Some("computation"),
        "newsroom_network_reduce" => Some("computation"),
        "newsroom_infographic_preview" => Some("visual"),
        "newsroom_infographic_vision_critic" => Some("visual"),
        "newsroom_infographic_revise" => Some("visual"),
        "newsroom_competition_preflight" => Some("publication"),
        "newsroom_chart" => Some("visual"),
        "record_claim" => Some("evidence"),
        _ => None,
    }
}

pub fn is_capability_class(class: Option<&str>) -> bool {
    matches!(
        class,
        Some("discovery" | "computation" | "evidence" | "synthesis" | "visual" | "publication")
    )
}
